### ISSUE TITLE
CentOS and RHEL 7.3: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1775] opened 2017-08-18 19:46 UTC
This seems to be ceph-ansible issue and fails for all CentOS 7.3 

"""
2017-08-18T19:07:25.922 INFO:teuthology.orchestra.run.vpm073.stdout:TASK [ceph-common : template ceph_conf_overrides] ******************************
2017-08-18T19:07:25.937 INFO:teuthology.orchestra.run.vpm073.stdout:task path: /home/ubuntu/ceph-ansible/roles/ceph-common/tasks/generate_ceph_conf.yml:13
2017-08-18T19:07:25.953 INFO:teuthology.orchestra.run.vpm073.stdout:fatal: [vpm039.front.sepia.ceph.com -> localhost]: FAILED! => {
2017-08-18T19:07:25.955 INFO:teuthology.orchestra.run.vpm073.stdout:    "changed": false,
2017-08-18T19:07:25.957 INFO:teuthology.orchestra.run.vpm073.stdout:    "checksum": "bda64e7c87f0fa320cb7c1cab9f8433e625d527c",
2017-08-18T19:07:25.959 INFO:teuthology.orchestra.run.vpm073.stdout:    "failed": true
2017-08-18T19:07:25.962 INFO:teuthology.orchestra.run.vpm073.stdout:}
2017-08-18T19:07:25.964 INFO:teuthology.orchestra.run.vpm073.stdout:
2017-08-18T19:07:25.966 INFO:teuthology.orchestra.run.vpm073.stdout:MSG:
2017-08-18T19:07:25.998 INFO:teuthology.orchestra.run.vpm073.stdout:
2017-08-18T19:07:26.000 INFO:teuthology.orchestra.run.vpm073.stdout:Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
2017-08-18T19:07:26.009 INFO:teuthology.orchestra.run.vpm073.stdout:
2017-08-18T19:07:26.013 INFO:teuthology.orchestra.run.vpm073.stdout:NO MORE HOSTS LEFT *************************************************************
2017-08-18T19:07:26.015 INFO:teuthology.orchestra.run.vpm073.stdout:
2017-08-18T19:07:26.018 INFO:teuthology.orchestra.run.vpm073.stdout:PLAY RECAP *********************************************************************
2017-08-18T19:07:26.020 INFO:teuthology.orchestra.run.vpm073.stdout:vpm039.front.sepia.ceph.com : ok=44   changed=13   unreachable=0    failed=1
2017-08-18T19:07:26.022 INFO:teuthology.orchestra.run.vpm073.stdout:vpm073.front.sepia.ceph.com : ok=40   changed=12   unreachable=0    failed=0
2017-08-18T19:07:26.024 INFO:teuthology.orchestra.run.vpm073.stdout:vpm129.front.sepia.ceph.com : ok=40   changed=11   unreachable=0    failed=0
"""

Full logs:  http://qa-proxy.ceph.com/teuthology/vasu-2017-08-18_18:40:24-ceph-ansible-master-distro-basic-vps/1538243/teuthology.log

**Comment by leseb** [comment] 2017-08-22 18:00
did you try to install `libselinux-python`?

**Comment by djgalloway** [comment] 2017-08-22 18:25
@leseb I just spent the last hour or so tracking this down.  https://github.com/ceph/ceph-ansible/pull/1018 introduced a bug where the `local_action` fails because ansible is being run in a virtualenv and system package python modules aren't imported.

```
TASK [ceph-common : template ceph_conf_overrides] ******************************
task path: /home/jenkins-build/build/workspace/rhcs-next-tests-rhcs-ansible2.2-dmcrypt_journal/roles/ceph-common/tasks/generate_ceph_conf.yml:13
fatal: [mon0 -> localhost]: FAILED! => {
    "changed": false, 
    "checksum": "3a0c273c2139e9dee7fa0ad017e740b5725b69a2", 
    "failed": true
}

MSG:

Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/jenkins-build/build/workspace/rhcs-next-tests-rhcs-ansible2.2-dmcrypt_journal/site.yml.retry

PLAY RECAP *********************************************************************
mgr0                       : ok=2    changed=0    unreachable=0    failed=0   
mon0                       : ok=27   changed=6    unreachable=0    failed=1   
osd0                       : ok=2    changed=0    unreachable=0    failed=0  
```

I've confirmed libselinux-python is indeed installed on the slave and in the vagrant VMs that get created.

I came across this which sort of sounds like our environment: https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/

I activated the virtualenv of a failed job and sure enough, there is no selinux module available.

```
root@rhcs-next1 rhcs-ansible2.2-dmcrypt_journal]# pwd
/tmp/tox.diXNKtCyHo/rhcs-ansible2.2-dmcrypt_journal

[root@rhcs-next1 rhcs-ansible2.2-dmcrypt_journal]# source bin/activate

(rhcs-ansible2.2-dmcrypt_journal) [root@rhcs-next1 rhcs-ansible2.2-dmcrypt_journal]# which python
/tmp/tox.diXNKtCyHo/rhcs-ansible2.2-dmcrypt_journal/bin/python

(rhcs-ansible2.2-dmcrypt_journal) [root@rhcs-next1 rhcs-ansible2.2-dmcrypt_journal]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import selinux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named selinux

```

Possible solution here but I'm out of my comfort zone at this point.  https://github.com/trailofbits/algo/issues/356#issuecomment-294090758

**Comment by vasukulkarni** [comment] 2017-08-22 19:45
@djgalloway thanks, I originally had systemstie packages enabled but it was knocked down in review, I can look into adding that in venv or enabling systemsite pckages.

**Comment by vasukulkarni** [comment] 2017-08-22 19:53
I have updated to use systemsite package and going to rerun, Also if we can provide rpm/deb packages it would take away all that unneeded complexity.

**Comment by vasukulkarni** [comment] 2017-08-22 20:36
using system-site packages is working!, closing this.

**Comment by djgalloway** [comment] 2017-08-23 16:56
@vasukulkarni Can you show where you configured that please?

**Comment by vasukulkarni** [comment] 2017-08-23 17:12
@djgalloway  here: https://github.com/ceph/teuthology/pull/1101/commits/ff779e420b611488f4bfc52b9873a9ba9a6cde65  but it seems to be breaking purge-cluster for some runs.

**Comment by djgalloway** [comment] 2017-08-23 18:11
This is still breaking downstream tests and would also fail on upstream tests if we were using CentOS slaves.  I've tried adding `rhcs: sitepackages=True` to tox.ini in what I think is the appropriate place but tests continue to fail.

**Comment by vasukulkarni** [comment] 2017-08-23 18:14
I have also opened following ticket to get the deb package https://github.com/ceph/ceph-ansible/issues/1792,  would prefer to use rpm/deb installation method than git clone + virtualenv and resolve dependenies.

**Comment by vasukulkarni** [comment] 2017-08-23 20:14
As seen here xenial runs fine, http://pulpito.ceph.com/vasu-2017-08-23_18:56:28-ceph-ansible-master-distro-basic-vps/ (some xenial are just workunit issues) but *all* centos fails, i included 'selinux' inside virtualenv in this run.

**Comment by djgalloway** [comment] 2017-08-23 20:17
> i included 'selinux' inside virtualenv in this run.

The selinux libs needed for ansible's `local_action` aren't available in a pip package.  That's what makes this so difficult.

**Comment by vasukulkarni** [comment] 2017-08-23 20:46
If I enable system-site-packages it works on centos but breaks the purge-cluster!

**Comment by ragingpastry** [comment] 2017-08-24 14:29
> The selinux libs needed for ansible's local_action aren't available in a pip package. That's what makes this so difficult.

Is there a reason they aren't a pip package? I've run into this issue before and like your link said it can be resolved by copying the selinux module from /usr/lib64/python2.7/site-packages into the virtualenv. Obviously not the solution here but could we simply make a pip package for it?

Or would specifically setting ansible_python_interpreter to /usr/bin/python for localhost work? I apologize if these solutions don't make sense here. I have not had the time to delve into ceph-ansible too much, but I am held up by this bug and would like to throw in my two cents.

**Closed** 2017-08-28 17:04 UTC

**Comment by djgalloway** [comment] 2017-08-28 17:18
@ragingpastry We're probably not the right people to ask about why selinux-policy isn't in a pip package.

Perhaps you can open an issue with the selinux folks: https://github.com/SELinuxProject/selinux/issues

**Comment by zoobab** [comment] 2018-09-06 11:29
Still no pip package?

**Comment by marsavela** [comment] 2018-09-07 15:55
I am looking for this as well.

**Comment by hsg777** [comment] 2019-08-20 16:49
Is there any resolution available?

**Comment by goodtimetribe** [comment] 2020-08-13 03:53
I was using Python 3 on CentOS 7 and encountering this error. I struggled with it and didn't find a specific solution here, so I'm sharing how I resolved it.

I installed the correct package... there's a package for Python2 and another for Python3.

```bash
sudo yum -y install libselinux-python3
```
