### ISSUE TITLE
purge-cluster.yml - colocated scenario fails because of no lvm_volumes var definition

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1887] opened 2017-09-13 14:06 UTC
purge-cluster.yml breaks again due in **osd_scenario: collocated** because **lvm_volumes** var is undefined, but it should not have to be defined in this scenario.
```
TASK [remove osd logical volumes] *******************************************************************************************************************************************
fatal: [192.168.121.64]: FAILED! => {"failed": true, "msg": "'lvm_volumes' is undefined"}
fatal: [192.168.121.112]: FAILED! => {"failed": true, "msg": "'lvm_volumes' is undefined"}
fatal: [192.168.121.158]: FAILED! => {"failed": true, "msg": "'lvm_volumes' is undefined"}
```
Surprisingly the when clause does not protect ansible from evaluating the variable lvm_volumes.  Is this another ansible bug?  Seems like it should evaluate the when clause first, then the with_items clause.

But in the meantime, we need to define lvm_volumes to the empty list in this case.  I worked around by setting lvm_volumes: []  but this is ugly.

**Comment by andrewschoen** [comment] 2017-09-13 18:25
@bengland2 what version of ansible and ceph-ansible are you using? I agree that it does kind of sound like an ansible bug. I just ran a test using ansible 2.3.1 and ceph-ansible@master and did not reproduce this issue though.

Here's the purge cluster test that passed: https://2.jenkins.ceph.com/view/ceph-ansible/job/ceph-ansible-scenario/16/console

**Comment by bengland2** [comment] 2017-09-13 19:11
I'm running ansible-2.3.2.0-1.fc26.noarch.   I noticed your Jenkins job Ceph VMs ran on Xenial not Centos,   and my laptop, where ansible runs, is Fedora 26 not Xenial.  But I'm using vagrant just like you are.  I have no idea why my test failed and yours passed.  Here's the simplest reproducer - no roles, no includes, just one var, no dependencies at all on other files.

```
---
- name: trivial play illustrating bug
  hosts: localhost
  vars:
          osd_scenario: collocated
  tasks:
          - name: task illustrating bug
            when: osd_scenario != "lvm"
            with_items: "{{ lvm_volumes }}"
            shell: "echo hi there"
```
and its output:
```
[bengland@bene-laptop ceph-ansible]$ pushd /tmp
/tmp ~/vagrant/ceph-ansible ~/vagrant/libvirt
[bengland@bene-laptop tmp]$ ansible-playbook -u root -i ../libvirt/host.inv t.yml
 [WARNING]: Host file not found: ../libvirt/host.inv

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [trivial play illustrating bug] ****************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [localhost]

TASK [task illustrating bug] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'lvm_volumes' is undefined"}
        to retry, use: --limit @/tmp/t.retry

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by bengland2** [comment] 2017-09-13 20:19
I was using ansible-2.3.2.0-1.fc26.noarch.  I looked at  your ci job log and it does not show the problem, but I can't tell if lvm_volumes was somehow defined in there.  I reproduce the problem using this simple playbook:

```
---
- name: trivial play illustrating bug
  hosts: localhost
  vars:
          osd_scenario: collocated
  tasks:
          - name: task illustrating bug
            when: osd_scenario != "lvm"
            with_items: "{{ lvm_volumes | default([]) }}"
            shell: "echo hi there"
```
and get this result:
```
[bengland@bene-laptop ceph-ansible]$ ansible-playbook -u root -i ../libvirt/host.inv t.yml

PLAY [trivial play illustrating bug] ****************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [localhost]

TASK [task illustrating bug] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'lvm_volumes' is undefined"}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```
But if I replace when clause with this:

```
            with_items: "{{ lvm_volumes | default([]) }}"
```
Then it works fine.  I read in ansible [issue 17484](https://github.com/ansible/ansible/issues/17484#issuecomment-245934305) that this is not a bug.  So I think this is the correct fix.

**Comment by bengland2** [comment] 2017-09-13 21:50
Sure that works for me, instead of inserting Jinja2 default filter
everywhere we can do it one time up front.

Could we add this to roles/ceph-defaults/tasks/facts.yml and put

roles:
- ceph-defaults

in the OSD play within purge-cluster.yml and any other playbook that deals
with OSDs, that way we don't have to add this kind of defaulting logic for
OSD vars to every playbook.   I've tried this in the past and it worked,
never got it upstream though.  I think this was Seb's comment on a PR that
I wrote.

**Comment by andrewschoen** [comment] 2017-09-14 13:21
@bengland2 actually, that's exactly why the ``ceph-defaults`` role was created. That's a much better solution than defaulting these values manually in the playbook, and it'll be updated automatically for us as new config options are added.

**Comment by bengland2** [comment] 2017-09-15 19:16
@andrewschoen unfortunately that wasn't good enough - I then hit a failure because osd_scenario var was undefined!  This is not fixable in ceph-defaults - have to pull in user-specified value of this variable.  This seemed to work well, found in examples for include_vars clause in ansible docs.  Does it make sense to you?

```
diff --git a/infrastructure-playbooks/purge-cluster.yml b/infrastructure-playbooks/purge-cluster.yml
index df82a358..f386c4d8 100644
--- a/infrastructure-playbooks/purge-cluster.yml
+++ b/infrastructure-playbooks/purge-cluster.yml
@@ -194,6 +194,12 @@
 
   tasks:
 
+  - name: pull in user-specified OSD vars
+    include_vars: "{{ item }}"
+    with_first_found:
+      - ../group_vars/osds.yml
+      - ../group_vars/osds
+
   - name: get osd numbers
     shell: "if [ -d /var/lib/ceph/osd ] ; then ls /var/lib/ceph/osd | sed 's/.*-//' ; fi"
     register: osd_ids
```
But I wasn't satisfied, this is a per-playbook change, wanted a way to fix it for everyone.  So I tried this:

```
diff --git a/roles/ceph-defaults/tasks/main.yml b/roles/ceph-defaults/tasks/main.yml
index 25887efa..3a94a425 100644
--- a/roles/ceph-defaults/tasks/main.yml
+++ b/roles/ceph-defaults/tasks/main.yml
@@ -1,3 +1,10 @@
 ---
+
+- name: pull in user-specified OSD vars
+  include_vars: "{{ item }}"
+  with_first_found:
+      - ../group_vars/osds.yml
+      - ../group_vars/osds
+
 - include: facts.yml
 - include: check_socket.yml
```
And that seemed to work as well.  So any playbook that includes ceph-defaults role will get this, right?    Will try to come up with PR but if I don't quickly enough, at least you know how I would try to fix it.

**Comment by andrewschoen** [comment] 2017-09-15 19:24
@bengland2 we really don't want to be including ``group_vars/`` like that. Ansible should pull that in automatically if you have ``group_vars/`` relative to your inventory or the playbook being run.

I'm assuming you had ``osd_scenario`` defined in your config somewhere, where was it located? Where did you include the ``ceph-defaults`` role? I wouldn't think that including a role would override config defined in ``group_vars/``.

**Comment by bengland2** [comment] 2017-09-15 20:02
@andrewschoen , yes this is very counter-intuitive that you have to do this.  My **osd_scenario** var was defined in **ceph-ansible/group_vars/osds.yml**.  But it didn't get pulled in!   I think the reason is that I don't include the **ceph-osds** role ever in **purge-cluster.yml** - doing so would trigger OSD creation which we don't want.  I just want OSD-related vars, nothing else.   I do pull in **ceph-defaults** as described above because that role takes no action, it just defines facts.  I don't have to do this with **ceph-ansible/group_vars/all.yml**, that seems to get pulled in automatically just fine.  So if we didn't have a separate **osds.yml**, then this would not be necessary.  Is this analysis correct?  Thx for helping me understand this better.

I retested and found that using relative pathname ../group_vars/osds.yml was insufficient, this doesn't work for site.yml because it's not in same directory as purge-cluster.yml.  So I changed to:
```
+
+- name: pull in user-specified OSD vars
+  include_vars: "{{ item }}"
+  with_first_found:
+      - group_vars/osds.yml
+      - group_vars/osds
+
```
And do this:
```
cd ceph-ansible/infrastructure-playbooks
ln -s ../group_vars .
```
it works.  We could do a similar thing for infrastructure_playbooks/untested_by_ci/   and these softlinks could be pre-populated in git repo, yes?

**Comment by andrewschoen** [comment] 2017-09-15 20:32
@bengland2 you can also just copy purge-cluster.yml to the root of ceph-ansible and it should use the ``group_vars/`` in the root of ceph-ansible then if that's where you like to keep them. You are right that if there is no ``hosts: osds`` anywhere in the playbook then config defined in ``group_vars/osds.yml`` will not be used.

Typically I like to keep a ``group_vars/`` directory relative to my inventory file so I know my config will always be used. This is how we manage all of our CI testing scenarios.

We don't want to use ``include_vars`` at all in these playbooks because doing so can override config options set elsewhere as ``include_vars`` in a playbook has very high variable precedence.

**Comment by bengland2** [comment] 2017-09-18 01:26
@andrewschoen, I had **osd_scenario** properly defined in **ceph-ansible/group_vars/osds.yml**  .    there was a **hosts: osds** or equivalent in that play within the OSD play in the purge-cluster.yml playbook, but **gather_facts: no** was used, which apparently inhibited reading **group_vars/osds.yml** .  When I removed **include_vars** statement above and also dropped **gather_facts** (which defaults to true) in the OSD play, it worked! so I think this is the best solution now, do you agree?

To see this, use this example playbook:
```
--- 
- name: see if osd_scenario is defined 

 roles: 
 - ceph-defaults 
 hosts: 
   - osds 

 gather_facts: false

 become: true 

 tasks: 

 - name: use osd_scenario 
   shell: "echo {{ osd_scenario }}"
```

This will fail but if you remove the **gather_facts** statement, it will work.

**Comment by andrewschoen** [comment] 2017-09-18 15:34
@bengland2 actually, using ``ceph-defaults`` here won't work because the osd configuration does not exist in ``ceph-defaults``, it's only in ``ceph-osd``.

Could you try this PR and see if it fixes things for you? https://github.com/ceph/ceph-ansible/pull/1916

**Comment by bengland2** [comment] 2017-09-22 13:50
@andrewschoen I think this fixes it for purge-cluster.yml.  if we could do this kind of fix in ceph-defaults role so that all playbooks could inherit it but maybe later.

**Comment by andrewschoen** [comment] 2017-09-28 14:55
fixed by https://github.com/ceph/ceph-ansible/pull/1916

**Closed by andrewschoen** 2017-09-28 14:55 UTC
