### ISSUE TITLE
ceph-config: set_fact num_osds fails because of variable parsing

### ISSUE THREAD

**Issue by alijahnas** [ceph/ceph-ansible#3431] opened 2018-12-10 13:44 UTC
In ceph-config, the task "run 'ceph-volume lvm batch --report" to see how many osds are to be created' registers result to lvm_batch_report.

Then next task "set_fact num_osds from the output of 'ceph-volume lvm batch --report'" fails because:
"The conditional check '(lvm_batch_report.stdout | from_json).changed' failed. The error was: error while evaluating conditional ((lvm_batch_report.stdout | from_json).changed): 'dict object' has no attribute 'changed'\n\nThe error appears to have been in '/home/ali/kube/ceph-ansible/roles/ceph-config/tasks/main.yml': line 54, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: set_fact num_osds from the output of 'ceph-volume lvm batch --report'\n      ^ here\n"

Variable lvm_batch_report is {'stderr_lines': [], u'changed': True, u'end': u'2018-12-10 13:33:31.095354', 'failed': False, u'stdout': u'{\\n    \"osds\": [\\n        {\\n            \"block.db\": {}, \\n            \"data\": {\\n                \"human_readable_size\": \"5.00 GB\", \\n                \"parts\": 1, \\n                \"path\": \"/dev/vdb\", \\n                \"percentage\": 100, \\n                \"size\": 5368709120.0\\n            }\\n        }\\n    ], \\n    \"vgs\": []\\n}', u'cmd': [u'ceph-volume', u'--cluster', u'ceph', u'lvm', u'batch', u'--bluestore', u'--yes', u'/dev/vdb', u'--report', u'--format=json'], u'start': u'2018-12-10 13:33:30.889313', u'delta': u'0:00:00.206041', u'stderr': u'', u'rc': 0, 'stdout_lines': [u'{', u'    \"osds\": [', u'        {', u'            \"block.db\": {}, ', u'            \"data\": {', u'                \"human_readable_size\": \"5.00 GB\", ', u'                \"parts\": 1, ', u'                \"path\": \"/dev/vdb\", ', u'                \"percentage\": 100, ', u'                \"size\": 5368709120.0', u'            }', u'        }', u'    ], ', u'    \"vgs\": []', u'}']}"
}

And (lvm_batch_report.stdout | from_json) is : {u'osds': [{u'block.db': {}, u'data': {u'path': u'/dev/vdb', u'percentage': 100, u'parts': 1, u'human_readable_size': u'5.00 GB', u'size': 5368709120.0}}], u'vgs': []}"

The condition should be "lvm_batch_report.changed", but is it maybe an ansible error on my side?

Ubuntu 18.04
Ansible version 2.6.10
ceph-ansible stable 3.2
Ceph Mimic 13.2.2

**Comment by ktwe** [comment] 2018-12-10 19:46
I guess the issue is already discussed in 
https://github.com/ceph/ceph-ansible/pull/3289. Conclusion seems to be, that the lvm scenario of stable-3.2 requires some functionality that has not been released yet.

**Comment by guits** [comment] 2018-12-11 14:17
based on #3289 I think we can close this issue.

Feel free to reopen if you have any concern.

**Closed by guits** 2018-12-11 14:17 UTC
