### ISSUE TITLE
file conflicts with ceph-iscsi-ansible

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#1031] opened 2016-10-12 17:06 UTC
I cannot "yum install" ceph-ansible 1.0.8 with [ceph-iscsi-ansible](https://github.com/pcuzner/ceph-iscsi-ansible) 1.1:

```
Transaction check error:
  file /usr/share/ceph-ansible/roles/ceph-iscsi-gw/tasks/main.yml from install of ceph-iscsi-ansible-1.0-1.el7.noarch conflicts with file from package ceph-ansible-1.0.8-1.el7scon.noarch
```

There are some placeholder files in ceph-ansible's `/roles/ceph-iscsi-gw` that conflict with the contents of ceph-iscsi-ansible. Would you please remove the conflicting files from ceph-ansible? (You can add the conflicting files back in if ceph-iscsi-ansible ever completely merges into ceph-ansible.)

CC'ing @pcuzner

**Comment by leseb** [comment] 2016-10-13 14:44
@ktdreyer is it an issue from https://github.com/pcuzner/ceph-iscsi-ansible?

**Comment by ktdreyer** [comment] 2016-10-13 15:02
@leseb right, I think we should delete the `/roles/ceph-iscsi-gw` files from ceph-ansible's tree, until pcuzner's code is merged into this repo.

**Comment by leseb** [comment] 2016-10-14 09:24
I'm just not sure to follow what's the root cause of the issue but if it's easier then let's remove the role for now. Can you send a PR for this?

**Comment by leseb** [comment] 2017-06-26 09:33
Fixed by https://github.com/ceph/ceph-ansible/pull/1586

**Closed by leseb** 2017-06-26 09:33 UTC
