### ISSUE TITLE
'Task' object has no attribute 'first_available_file'

### ISSUE THREAD

**Issue by wind0204** [ceph/ceph-ansible#1037] opened 2016-10-18 08:39 UTC
I have to say this issue is old, like 8 days ( https://github.com/ceph/ceph-ansible/issues/1003  )
I'm planning to configure some clusters using ansible including ceph clusters. and I've thought ceph-ansible would be great.
but a few errors occurred; fixed them one by one but the last one wasn't easy enough for me to fix.

what I did :

> $ git clone https://github.com/ceph/ceph-ansible/
> $ cd ceph-ansible
> $ sudo apt-get install libyaml-dev libpython2.7-dev libffi-dev libssl-dev 
> $ sudo ./install-ansible.sh 
> $ pip install --upgrade setuptools
> $ rm -rf ansible
> $ sudo ./install-ansible.sh 
> edited /etc/ansible/hosts
> followed the wiki ( https://github.com/ceph/ceph-ansible/wiki )
> (and tried stable-2.2, stable-2.1, stable-2.0, stable-1.9 of the ansible git repository in vain and found out that these versions all just show different error messages not succeeding)

The error messages with current devel branch after issuing 'cd ~/ceph-ansible && ansible-playbook ~/ceph-ansible/site.yml' and to see the details 'ansible-playbook -vvv --limit @/home/doeals0/ceph-ansible/site.retry ~/ceph-ansible/site.yml' :

> TASK [ceph.ceph-common : generate ceph configuration file] *********************
> 
> task path: /home/doeals0/ceph-ansible/roles/ceph-common/tasks/main.yml:230
> <peta-s-227> ESTABLISH SSH CONNECTION FOR USER: ansibled
> <peta-s-227> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssap
> i-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibled -o ConnectTimeout=10 -o ControlPath=/home/doeals0/.ansible/cp/ansible-ssh-%h-%p-%r p
> eta-s-227 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1476772273.61-127685044050676`" && echo ansible-tmp-1476772273.61-12
> 7685044050676="`echo $HOME/.ansible/tmp/ansible-tmp-1476772273.61-127685044050676`" ) && sleep 0'"'"''
> <0-h0> ESTABLISH SSH CONNECTION FOR USER: ansibled
> <0-h0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keye
> x,hostbased,publickey -o PasswordAuthentication=no -o User=ansibled -o ConnectTimeout=10 -o ControlPath=/home/doeals0/.ansible/cp/ansible-ssh-%h-%p-%r 0-h0 '/
> bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1476772273.62-28507860882019`" && echo ansible-tmp-1476772273.62-28507860882019=
> "`echo $HOME/.ansible/tmp/ansible-tmp-1476772273.62-28507860882019`" ) && sleep 0'"'"''
> 
> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 122, in run
>     res = self._execute()
>   File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 488, in _execute
>     result = self._handler.run(task_vars=variables)
>   File "/home/doeals0/ceph-ansible/plugins/actions/_v2_config_template.py", line 481, in run
>     _status, _vars = self._load_options_and_status(task_vars=task_vars)
>   File "/home/doeals0/ceph-ansible/plugins/actions/_v2_config_template.py", line 419, in _load_options_and_status
>     faf = self._task.first_available_file
> AttributeError: 'Task' object has no attribute 'first_available_file'
> 
> fatal: [peta-s-227]: FAILED! => {
>     "failed": true, 
>     "msg": "Unexpected failure during module execution.", 
>     "stdout": ""
> }
> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 122, in run
>     res = self._execute()
>   File "/usr/local/lib/python2.7/dist-packages/ansible-2.3.0-py2.7.egg/ansible/executor/task_executor.py", line 488, in _execute
>     result = self._handler.run(task_vars=variables)
>   File "/home/doeals0/ceph-ansible/plugins/actions/_v2_config_template.py", line 481, in run
>     _status, _vars = self._load_options_and_status(task_vars=task_vars)
>   File "/home/doeals0/ceph-ansible/plugins/actions/_v2_config_template.py", line 419, in _load_options_and_status
>     faf = self._task.first_available_file
> AttributeError: 'Task' object has no attribute 'first_available_file'
> 
> fatal: [0-h0]: FAILED! => {
>     "failed": true, 
>     "msg": "Unexpected failure during module execution.", 
>     "stdout": ""
> }
>         to retry, use: --limit @/home/doeals0/ceph-ansible/site.retry
> 
> PLAY RECAP *********************************************************************
> 0-h0                       : ok=29   changed=0    unreachable=0    failed=1  
> peta-s-227                 : ok=30   changed=0    unreachable=0    failed=1   

the machine was configured:
 with Debian Jessie.

I'm totally new to this world of administration so any help would be appreciated much.

Best Wishes
From Korea

**Comment by wind0204** [comment] 2016-10-18 14:45
I assume that ceph-ansible developers are aware of this change in ansible : "The first_available_file option on tasks has been deprecated. Users should use the with_first_found option or lookup (‘first_found’, …) plugin." from https://docs.ansible.com/ansible/porting_guide_2.0.html#deprecated

**Comment by analbeard** [comment] 2016-10-18 19:39
Yup, this is pretty much a duplicate of where I got to. 

I would note that I have actually now gotten this to work this evening, but it involved me going back to 2.0. In my install-ansible.sh I amended the ansible checkout to read `git clone -b stable-2.0 https://github.com/ansible/ansible.git`, and voila.

**Comment by wind0204** [comment] 2016-10-19 02:39
@analbeard that seems the right way to move on for the moment.

As I wrote I had tried stable-2.0 but by just doing 'git checkout stable-2.0' and read some error messages and moved on to another branch...

This time, I cloned ansible with stable-2.0 and did run the 'git submodule update --init --recursive' and got it; though I was just hit by another issue :(

**Comment by leseb** [comment] 2016-10-20 09:11
Can we close this then?

**Comment by analbeard** [comment] 2016-10-20 09:15
@leseb it's still going to be a problem with v2.1 and upwards - _v2_config_template.py uses functions which no longer exist. I can take a stab at fixing it, but it'll be akin to someone flailing wildly and happening on the solution more by good luck that judgement ;)

**Comment by leseb** [comment] 2016-10-25 10:25
Hum yes please do, don't hesitate to ping @cloudnull when it comes to config_template as he is the maintainer/main dev of if.

**Comment by cloudnull** [comment] 2016-10-25 15:41
@leseb and @analbeard please review https://github.com/ceph/ceph-ansible/pull/1048 when you have a chance as we're patched the config_template to allow for 2.2 compatibility.

**Comment by analbeard** [comment] 2016-10-26 13:14
Commented the PR, but that works under 2.2 for me. Thanks!

**Closed** 2016-10-31 10:25 UTC
