### ISSUE TITLE
Error EINVAL: key for mgr.vpm103 exists but cap mds does not match

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1480] opened 2017-04-27 21:45 UTC
I have monitor and mgr running on same node and I see the following issue

Full logs:
http://qa-proxy.ceph.com/teuthology/vasu-2017-04-27_19:27:10-smoke-master---basic-vps/1074173/teuthology.log

```
2017-04-27T21:00:16.759 INFO:teuthology.orchestra.run.vpm103.stdout:ok: [vpm103.front.sepia.ceph.com] => {"changed": false, "cmd": ["ceph", "--cluster", "ceph", "config-key", "put", "initial_mon_keyring", "AQDDWwJZAAAAABAAfMyIosPzdaiqxO/aZO/gEA=="], "delta": "0:00:00.304052", "end": "2017-04-27 21:00:16.797395", "rc": 0, "start": "2017-04-27 21:00:16.493343", "stderr": "2017-04-27 21:00:16.623947 7faf56eef700  1  Processor -- start\n2017-04-27 21:00:16.623989 7faf56eef700  1 -- - start start\n2017-04-27 21:00:16.624725 7faf56eef700  1 -- - --> 172.21.2.103:6789/0 -- auth(proto 0 34 bytes epoch 0) v1 -- 0x7faf5011cc80 con 0\n2017-04-27 21:00:16.625337 7faf4ffff700  1 -- 172.21.2.103:0/828437377 learned_addr learned my addr 172.21.2.103:0/828437377\n2017-04-27 21:00:16.625871 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 1 ==== mon_map magic: 0 v1 ==== 188+0+0 (3710216326 0 0) 0x7faf48000ae0 con 0x7faf5011eb00\n2017-04-27 21:00:16.625932 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 2 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 33+0+0 (51951360 0 0) 0x7faf48001590 con 0x7faf5011eb00\n2017-04-27 21:00:16.626044 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- auth(proto 2 32 bytes epoch 0) v1 -- 0x7faf3c001470 con 0\n2017-04-27 21:00:16.626610 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 3 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 206+0+0 (404788191 0 0) 0x7faf48001170 con 0x7faf5011eb00\n2017-04-27 21:00:16.626694 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- auth(proto 2 165 bytes epoch 0) v1 -- 0x7faf3c001d00 con 0\n2017-04-27 21:00:16.627128 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 4 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 564+0+0 (3858978013 0 0) 0x7faf480019a0 con 0x7faf5011eb00\n2017-04-27 21:00:16.627277 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- mon_subscribe({monmap=0+}) v2 -- 0x7faf5011bba0 con 0\n2017-04-27 21:00:16.627496 7faf56eef700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- mon_subscribe({mgrmap=0+}) v2 -- 0x7faf500b3e60 con 0\n2017-04-27 21:00:16.627559 7faf56eef700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- mon_subscribe({osdmap=0}) v2 -- 0x7faf501224d0 con 0\n2017-04-27 21:00:16.629927 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 5 ==== mon_map magic: 0 v1 ==== 188+0+0 (3710216326 0 0) 0x7faf48001440 con 0x7faf5011eb00\n2017-04-27 21:00:16.629975 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 6 ==== mgrmap(e 3) v1 ==== 68+0+0 (2659064817 0 0) 0x7faf480019a0 con 0x7faf5011eb00\n2017-04-27 21:00:16.630021 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 7 ==== osd_map(1..1 src has 1..1) v3 ==== 885+0+0 (1692779653 0 0) 0x7faf480022d0 con 0x7faf5011eb00\n2017-04-27 21:00:16.631042 7faf56eef700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- mon_command({\"prefix\": \"get_command_descriptions\"} v 0) v1 -- 0x7faf500e0b30 con 0\n2017-04-27 21:00:16.633876 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 8 ==== mon_command_ack([{\"prefix\": \"get_command_descriptions\"}]=0  v0) v1 ==== 72+0+46981 (1092875540 0 1532782332) 0x7faf48001170 con 0x7faf5011eb00\n2017-04-27 21:00:16.781338 7faf56eef700  1 -- 172.21.2.103:0/828437377 --> 172.21.2.103:6789/0 -- mon_command({\"prefix\": \"config-key put\", \"key\": \"initial_mon_keyring\", \"val\": \"AQDDWwJZAAAAABAAfMyIosPzdaiqxO/aZO/gEA==\"} v 0) v1 -- 0x7faf500e0ae0 con 0\n2017-04-27 21:00:16.783933 7faf4e7fc700  1 -- 172.21.2.103:0/828437377 <== mon.0 172.21.2.103:6789/0 9 ==== mon_command_ack([{\"prefix\": \"config-key put\", \"key\": \"initial_mon_keyring\", \"val\": \"AQDDWwJZAAAAABAAfMyIosPzdaiqxO/aZO/gEA==\"}]=0 value stored v0) v1 ==== 155+0+0 (2720834368 0 0) 0x7faf480019a0 con 0x7faf5011eb00\nvalue stored\n2017-04-27 21:00:16.786534 7faf56eef700  1 -- 172.21.2.103:0/828437377 >> 172.21.2.103:6789/0 conn(0x7faf5011eb00 :-1 s=STATE_OPEN pgs=10 cs=1 l=1).mark_down\n2017-04-27 21:00:16.786872 7faf56eef700  1 -- 172.21.2.103:0/828437377 shutdown_connections \n2017-04-27 21:00:16.787591 7faf56eef700  1 -- 172.21.2.103:0/828437377 shutdown_connections \n2017-04-27 21:00:16.787675 7faf56eef700  1 -- 172.21.2.103:0/828437377 wait complete.\n2017-04-27 21:00:16.787693 7faf56eef700  1 -- 172.21.2.103:0/828437377 >> 172.21.2.103:0/828437377 conn(0x7faf5010dfb0 :-1 s=STATE_NONE pgs=0 cs=0 l=0).mark_down", "stdout": "", "stdout_lines": [], "warnings": []}
2017-04-27T21:00:16.760 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:16.760 INFO:teuthology.orchestra.run.vpm103.stdout:TASK [ceph-mon : create ceph rest api keyring when mon is not containerized] ***
2017-04-27T21:00:16.760 INFO:teuthology.orchestra.run.vpm103.stdout:task path: /home/ubuntu/ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml:36
2017-04-27T21:00:16.797 INFO:teuthology.orchestra.run.vpm103.stdout:skipping: [vpm103.front.sepia.ceph.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
2017-04-27T21:00:16.797 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:16.797 INFO:teuthology.orchestra.run.vpm103.stdout:TASK [ceph-mon : create ceph mgr keyring(s) when mon is not containerized] *****
2017-04-27T21:00:16.797 INFO:teuthology.orchestra.run.vpm103.stdout:task path: /home/ubuntu/ceph-ansible/roles/ceph-mon/tasks/ceph_keys.yml:46
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:failed: [vpm103.front.sepia.ceph.com] (item=vpm103.front.sepia.ceph.com) => {"changed": false, "cmd": ["ceph", "--cluster", "ceph", "auth", "get-or-create", "mgr.vpm103", "mon", "allow profile mgr", "osd", "allow *", "mds", "allow *", "-o", "/etc/ceph/ceph.mgr.vpm103.keyring"], "delta": "0:00:00.315298", "end": "2017-04-27 21:00:17.654612", "failed": true, "item": "vpm103.front.sepia.ceph.com", "rc": 22, "start": "2017-04-27 21:00:17.339314", "stderr": "2017-04-27 21:00:17.476135 7f55cafd4700  1  Processor -- start\n2017-04-27 21:00:17.476206 7f55cafd4700  1 -- - start start\n2017-04-27 21:00:17.476929 7f55cafd4700  1 -- - --> 172.21.2.103:6789/0 -- auth(proto 0 34 bytes epoch 0) v1 -- 0x7f55c411cd50 con 0\n2017-04-27 21:00:17.478102 7f55c885e700  1 -- 172.21.2.103:0/4061186876 learned_addr learned my addr 172.21.2.103:0/4061186876\n2017-04-27 21:00:17.478698 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 1 ==== mon_map magic: 0 v1 ==== 188+0+0 (3710216326 0 0) 0x7f55b40009b0 con 0x7f55c411ebd0\n2017-04-27 21:00:17.478781 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 2 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 33+0+0 (3159401033 0 0) 0x7f55b4001400 con 0x7f55c411ebd0\n2017-04-27 21:00:17.478877 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- auth(proto 2 32 bytes epoch 0) v1 -- 0x7f55b0001470 con 0\n2017-04-27 21:00:17.479455 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 3 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 206+0+0 (287731585 0 0) 0x7f55b4001090 con 0x7f55c411ebd0\n2017-04-27 21:00:17.479561 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- auth(proto 2 165 bytes epoch 0) v1 -- 0x7f55b0001d00 con 0\n2017-04-27 21:00:17.480008 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 4 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 564+0+0 (416881245 0 0) 0x7f55b4001800 con 0x7f55c411ebd0\n2017-04-27 21:00:17.480137 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- mon_subscribe({monmap=0+}) v2 -- 0x7f55c411bb70 con 0\n2017-04-27 21:00:17.480362 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- mon_subscribe({mgrmap=0+}) v2 -- 0x7f55c40b3f20 con 0\n2017-04-27 21:00:17.480431 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- mon_subscribe({osdmap=0}) v2 -- 0x7f55c41225a0 con 0\n2017-04-27 21:00:17.480956 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 5 ==== mon_map magic: 0 v1 ==== 188+0+0 (3710216326 0 0) 0x7f55b40009b0 con 0x7f55c411ebd0\n2017-04-27 21:00:17.480998 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 6 ==== mgrmap(e 3) v1 ==== 68+0+0 (2659064817 0 0) 0x7f55b40010d0 con 0x7f55c411ebd0\n2017-04-27 21:00:17.481043 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 7 ==== osd_map(1..1 src has 1..1) v3 ==== 885+0+0 (1692779653 0 0) 0x7f55b4002170 con 0x7f55c411ebd0\n2017-04-27 21:00:17.490086 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- mon_command({\"prefix\": \"get_command_descriptions\"} v 0) v1 -- 0x7f55c40b3f20 con 0\n2017-04-27 21:00:17.493189 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 8 ==== mon_command_ack([{\"prefix\": \"get_command_descriptions\"}]=0  v0) v1 ==== 72+0+46981 (1092875540 0 1532782332) 0x7f55b4001090 con 0x7f55c411ebd0\n2017-04-27 21:00:17.640927 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 --> 172.21.2.103:6789/0 -- mon_command({\"prefix\": \"auth get-or-create\", \"entity\": \"mgr.vpm103\", \"caps\": [\"mon\", \"allow profile mgr\", \"osd\", \"allow *\", \"mds\", \"allow *\"]} v 0) v1 -- 0x7f55c40b3ed0 con 0\n2017-04-27 21:00:17.641623 7f55c2ffd700  1 -- 172.21.2.103:0/4061186876 <== mon.0 172.21.2.103:6789/0 9 ==== mon_command_ack([{\"prefix\": \"auth get-or-create\", \"entity\": \"mgr.vpm103\", \"caps\": [\"mon\", \"allow profile mgr\", \"osd\", \"allow *\", \"mds\", \"allow *\"]}]=-22 key for mgr.vpm103 exists but cap mds does not match v7) v1 ==== 216+0+0 (2017881016 0 0) 0x7f55b4001800 con 0x7f55c411ebd0\nError EINVAL: key for mgr.vpm103 exists but cap mds does not match\n2017-04-27 21:00:17.643969 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 >> 172.21.2.103:6789/0 conn(0x7f55c411ebd0 :-1 s=STATE_OPEN pgs=11 cs=1 l=1).mark_down\n2017-04-27 21:00:17.644328 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 shutdown_connections \n2017-04-27 21:00:17.644665 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 shutdown_connections \n2017-04-27 21:00:17.644741 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 wait complete.\n2017-04-27 21:00:17.644758 7f55cafd4700  1 -- 172.21.2.103:0/4061186876 >> 172.21.2.103:0/4061186876 conn(0x7f55c410e070 :-1 s=STATE_NONE pgs=0 cs=0 l=0).mark_down", "stdout": "", "stdout_lines": [], "warnings": []}
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : copy mon restart script] *******************
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mon daemon(s)] ****************
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.614 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : copy osd restart script] *******************
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph osds daemon(s)] ***************
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mdss] *************************
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph rgws] *************************
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.615 INFO:teuthology.orchestra.run.vpm103.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph nfss] *************************
2017-04-27T21:00:17.623 INFO:teuthology.orchestra.run.vpm103.stdout:	to retry, use: --limit @/home/ubuntu/ceph-ansible/site.retry
2017-04-27T21:00:17.623 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.623 INFO:teuthology.orchestra.run.vpm103.stdout:PLAY RECAP *********************************************************************
2017-04-27T21:00:17.623 INFO:teuthology.orchestra.run.vpm103.stdout:vpm103.front.sepia.ceph.com : ok=59   changed=23   unreachable=0    failed=1
2017-04-27T21:00:17.623 INFO:teuthology.orchestra.run.vpm103.stdout:
2017-04-27T21:00:17.759 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/run_tasks.py", line 89, in run_tasks
    manager.__enter__()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/task/__init__.py", line 121, in __enter__
    self.begin()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/task/ceph_ansible.py", line 203, in begin
    self.execute_playbook()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/task/ceph_ansible.py", line 154, in execute_playbook
    self.run_playbook()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/task/ceph_ansible.py", line 364, in run_playbook
    run.Raw(str_args)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/orchestra/remote.py", line 193, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/orchestra/run.py", line 414, in run
    r.wait()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/orchestra/run.py", line 149, in wait
    self._raise_for_status()
  File "/home/teuthworker/src/git.ceph.com_git_teuthology_wip-ansible-mgr/teuthology/orchestra/run.py", line 171, in _raise_for_status
    node=self.hostname, label=self.label
CommandFailedError: Command failed on vpm103 with status 2: 'cd ~/ceph-ansible ; virtualenv venv ; source venv/bin/activate ; pip install --upgrade pip ; pip install setuptools>=11.3 ansible==2.2.1 ; ansible-playbook -vv -i inven.yml site.yml'
2017-04-27T21:00:19.449 ERROR:teuthology.run_tasks: Sentry event: http://sentry.ceph.com/sepia/teuthology/?q=10a2a4f0b5a0459997301cefa316ed61
```

**Comment by vasukulkarni** [comment] 2017-04-28 17:31
@leseb @andrewschoen this is kind of blocker for ceph-ansible test and others that depend on it, would you mind looking at and redirect if its not ceph-anbile related, I have mon and mgr running on same node.

**Comment by andrewschoen** [comment] 2017-04-28 17:40
@vasukulkarni this looks like it might be related https://github.com/ceph/ceph-ansible/pull/1459

What branch are you testing with? That PR was not included in ``stable-2.2``. 

Perhaps @jcsp can tell us if this is the same issue that #1459 fixed.

**Comment by andrewschoen** [comment] 2017-04-28 17:42
Hmm, on closer look it does seem like the change from #1459 is in your teuthology log.

**Comment by vasukulkarni** [comment] 2017-04-28 17:47
@andrewschoen yes that change should be in, Both ceph-ansible and ceph are master branch and run yesterday.

**Comment by leseb** [comment] 2017-05-11 06:14
I think we are having this issue on the CI as well.
@vasukulkarni are you still experiencing this issue?

**Comment by martian111** [comment] 2017-05-11 11:04
I ran into this issue too.  After some time troubleshooting, I have the likely root cause, so wanted to share what I've found.

First, my setup:
I'm using a custom Yum repository containing the RPMs of a custom build of Ceph 12.0.X at https://github.com/ceph/ceph/commit/362c106c2c953fbf3027aad55bd46277b4a9f9db (2017-04-26).  

Then, I'm using ceph-ansible from GIT rev d8387cf82c647b85d51d5c28bd3a2c37f02ebd84 (2017-04-27) to deploy to my test servers.

After stepping through the playbook, I've found that the mgr.hostname key (stored in /var/lib/ceph/mgr/ceph-hostname) is created upon installation of ceph-mgr (TASK [ceph.ceph-common : install ceph mgr]).  As the playbook continues, it will fail with a message that is similar to the title of this issue/PR.  At that point, logging into the MGR host and `ceph auth get` on the offending key will show one capability, `caps mon = "allow profile mgr"`, instead of the expected:  `mon 'allow profile mgr' osd 'allow *' mds 'allow *'`

This mismatch is caused by two commits, one in ceph and one in ceph-ansible.  Though they are designed to work together, it appears they were merged at different times.
https://github.com/ceph/ceph/commit/43d26b914750513736918d52d45d2a42cdcc29e7 merged on 5/2/2017
https://github.com/ceph/ansible-ceph-mon/commit/3dea0830f755fc59845a724c1267dde741afb19d merged on 4/21/2017.

In my case, just out of (bad) luck, my work on 4/27 included the change in ceph-ansible, but not the corresponding change in ceph.  As a result, my RPMs created the mgr user with the older set of capabilities.  I assume if I updated both source trees, this problem would go away.

In the mean time, my workaround is to let the playbook fail.  Then, on the MGR host, manually modify the user capabilities with:
`ceph auth caps mgr.hostname mon 'allow profile mgr' osd 'allow *' mds 'allow *'`
Next, rerun the failed task command (otherwise, the keyring file would stay 0 bytes):  
`ceph --cluster ceph auth get-or-create mgr.hostname -o /etc/ceph/ceph.mgr.hostname.keyring`
Finally, run the playbook again and it completes successfully.

Not sure if this helps anyone as this seems to be a rare set of circumstances that lead to this error (for me at least).

**Comment by andrewschoen** [comment] 2017-05-11 11:17
@leseb @vasukulkarni I think that #1499 should have fixed this issue. That might depend on ``ceph_stable_release`` being set to ``jewel`` though.

**Comment by vasukulkarni** [comment] 2017-05-12 15:33
@andrewschoen thanks, but my run was on master not jewel, anyway I will retry this today again.

**Comment by leseb** [comment] 2017-07-03 12:55
No activity. Closing this, feel free to re-open.

**Closed by leseb** 2017-07-03 12:55 UTC
