### ISSUE TITLE
client install fatal due to 'pool_default_pg_num' is undefined" 

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1149] opened 2016-12-05 19:18 UTC
moved from ansible vesion 2.1 to 2.2, previously this used to work but now i see fatal during client playbook.

2016-12-05T19:10:14.400 INFO:teuthology.orchestra.run.vpm157.stdout:TASK [ceph-client : create pools] **********************************************
2016-12-05T19:10:14.417 INFO:teuthology.orchestra.run.vpm157.stdout:fatal: [vpm181.front.sepia.ceph.com]: FAILED! => {"failed": true, "msg": "[{u'name': u'test', u'pgs': u'{{ pool_default_pg_num }}'}, {u'name': u'test2', u'pgs': u'{{ pool_default_pg_num }}'}]: 'pool_default_pg_num' is undefined"}
2016-12-05T19:10:14.418 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.418 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mons] *************************
2016-12-05T19:10:14.418 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.418 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mons with systemd] ************
2016-12-05T19:10:14.419 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.419 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mons on ubuntu] ***************
2016-12-05T19:10:14.419 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.420 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph osds] *************************
2016-12-05T19:10:14.420 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.420 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph osds with systemd] ************
2016-12-05T19:10:14.420 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.420 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph osds on ubuntu] ***************
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mdss on ubuntu] ***************
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mdss] *************************
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.421 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph mdss with systemd] ************
2016-12-05T19:10:14.423 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.423 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph rgws on ubuntu] ***************
2016-12-05T19:10:14.423 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.423 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph rgws] *************************
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph rgws on red hat] **************
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph rgws with systemd] ************
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:RUNNING HANDLER [ceph.ceph-common : restart ceph nfss] *************************
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:    to retry, use: --limit @/home/ubuntu/ceph-ansible/site.retry
2016-12-05T19:10:14.424 INFO:teuthology.orchestra.run.vpm157.stdout:
2016-12-05T19:10:14.425 INFO:teuthology.orchestra.run.vpm157.stdout:PLAY RECAP *********************************************************************
2016-12-05T19:10:14.425 INFO:teuthology.orchestra.run.vpm157.stdout:vpm157.front.sepia.ceph.com : ok=111  changed=14   unreachable=0    failed=0
2016-12-05T19:10:14.425 INFO:teuthology.orchestra.run.vpm157.stdout:vpm163.front.sepia.ceph.com : ok=108  changed=13   unreachable=0    failed=0
2016-12-05T19:10:14.425 INFO:teuthology.orchestra.run.vpm157.stdout:vpm181.front.sepia.ceph.com : ok=38   changed=7    unreachable=0    failed=1

**Comment by keepwatch** [comment] 2016-12-05 21:19
This looks like a duplicate of #1145.

**Comment by vasukulkarni** [comment] 2016-12-06 00:14
@keepwatch  yep seems to be duplicate of 1145

**Comment by leseb** [comment] 2016-12-06 09:28
Closing because duplicate of #1145

**Closed by leseb** 2016-12-06 09:28 UTC
