### ISSUE TITLE
test with ansible 2.7

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#3170] opened 2018-09-25 19:27 UTC
Currently we test upstream in Jenkins with Ansible 2.5 and 2.6, as discussed in #2901

Please add testing for Ansible 2.7. Their [2.7.0rc3 prerelease](https://pypi.org/project/ansible/#history) is available.

Ansible 2.5 will go end-of-life after Ansible 2.7 is released (https://access.redhat.com/support/policy/updates/ansible-engine)

**Comment by guits** [comment] 2018-09-25 19:41
This is duplicate of #3148 and will be addressed by #3151 

I'm closing this

**Closed by guits** 2018-09-25 19:41 UTC
