### ISSUE TITLE
Failure at [ceph-osd : use ceph-volume lvm batch to create bluestore osds]

### ISSUE THREAD

**Issue by alphanoobmeric** [ceph/ceph-ansible#6243] opened 2021-02-04 16:36 UTC
**Bug Report**

What happened: Failure at [ceph-osd : use ceph-volume lvm batch to create bluestore osds]
This appears to be similar to #6160

Running command: /sbin/lvcreate --yes -l 715397 -n osd-block-913d663c-eab2-43a7-af69-2f91778d7715 ceph-3201e729-4f9e-43d8-b248-37565bf129d1
stderr: Volume group "ceph-3201e729-4f9e-43d8-b248-37565bf129d1" has insufficient free space (715396 extents): 715397 required.
    --> Was unable to complete a new OSD, will rollback changes

Is there a workaround to this? Somewhere I can set the extents myself, for now, so I can get the cluster setup?

**Environment**: 
* OS (e.g. from /etc/os-release): RHEL 8.3
* Kernel (e.g. `uname -a`): 4.18.0-240.el8.x86_64
* Ansible version (e.g. `ansible-playbook --version`): 2.9.17
* ceph-ansible version (e.g. `git head or tag or stable branch`): octopus

**Comment by dsavineau** [comment] 2021-02-04 16:52
This is a ceph-volume issue as metionned in the other issue.

Note that this was fixed in ceph@master and waiting to be backported into the stable release

For octopus : https://github.com/ceph/ceph/pull/39271

> Is there a workaround to this?

Maybe you can try to use ceph-volume lvm create/prepare instead of ceph-volume lvm batch via the `lvm_volumes` variable (instead of `devices`) and see if the issue is still present.

**Closed by dsavineau** 2021-02-04 16:52 UTC

**Comment by BojungKim** [comment] 2021-02-19 02:24
Use lvm_volumes !! Gooood!! :)
