### ISSUE TITLE
ceph-disk: Cannot discover filesystem type: device /dev/nvme0n1p1: Line is truncated:

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1661] opened 2017-07-07 01:19 UTC
I see 2 issues, one is the activation fails (I dont think it is a ceph-disk issue), since the ceph-osd activation has failed, the overall ansible should taks for osd should be fail but that is not the case, the playbook completes with no failure.

```
2017-07-06T22:40:50.446 INFO:teuthology.orchestra.run.smithi182.stdout:ok: [smithi107.front.sepia.ceph.com] => (item=[{'_ansible_parsed': True, u'cmd': u"readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'", u'end': u'2017-07-06 22:40:48.246119', '_ansible_no_log': False, u'stdout': u'/dev/nvme0n1p1', '_ansible_item_result': True, u'rc': 0, 'item': u'/dev/nvme0n1p1', u'delta': u'0:00:00.003514', u'stderr': u'', u'changed': False, 'invocation': {'module_name': u'command', u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u"readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'", u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [u'/dev/nvme0n1p1'], 'failed_when_result': False, u'start': u'2017-07-06 22:40:48.242605', u'warnings': [], 'failed': False}, '/dev/nvme0n1p1']) => {
2017-07-06T22:40:50.446 INFO:teuthology.orchestra.run.smithi182.stdout:    "changed": false,
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    "cmd": [
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:        "ceph-disk",
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:        "activate",
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:        "/dev/nvme0n1p1"
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    ],
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    "delta": "0:00:00.527006",
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    "end": "2017-07-06 22:40:50.425804",
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    "failed": false,
2017-07-06T22:40:50.447 INFO:teuthology.orchestra.run.smithi182.stdout:    "failed_when_result": false,
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:    "item": [
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:        {
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "_ansible_item_result": true,
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "_ansible_no_log": false,
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "_ansible_parsed": true,
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "changed": false,
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "cmd": "readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "delta": "0:00:00.003514",
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "end": "2017-07-06 22:40:48.246119",
2017-07-06T22:40:50.448 INFO:teuthology.orchestra.run.smithi182.stdout:            "failed": false,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:            "failed_when_result": false,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:            "invocation": {
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                "module_args": {
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "_raw_params": "readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "_uses_shell": true,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "chdir": null,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "creates": null,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "executable": null,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "removes": null,
2017-07-06T22:40:50.449 INFO:teuthology.orchestra.run.smithi182.stdout:                    "warn": true
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:                },
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:                "module_name": "command"
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            },
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "item": "/dev/nvme0n1p1",
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "rc": 0,
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "start": "2017-07-06 22:40:48.242605",
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "stderr": "",
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "stdout": "/dev/nvme0n1p1",
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:            "stdout_lines": [
2017-07-06T22:40:50.450 INFO:teuthology.orchestra.run.smithi182.stdout:                "/dev/nvme0n1p1"
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:            ],
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:            "warnings": []
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:        },
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:        "/dev/nvme0n1p1"
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:    ],
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:    "rc": 1,
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:    "start": "2017-07-06 22:40:49.898798",
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182 https://paste.fedoraproject.org/paste/j4EIRN6d60pcreH4X8Ejxg/raw.stdout:    "warnings": []
2017-07-06T22:40:50.451 INFO:teuthology.orchestra.run.smithi182.stdout:}
2017-07-06T22:40:50.452 INFO:teuthology.orchestra.run.smithi182.stdout:
2017-07-06T22:40:50.452 INFO:teuthology.orchestra.run.smithi182.stdout:STDERR:
2017-07-06T22:40:50.452 INFO:teuthology.orchestra.run.smithi182.stdout:
2017-07-06T22:40:50.452 INFO:teuthology.orchestra.run.smithi182.stdout:ceph-disk: Cannot discover filesystem type: device /dev/nvme0n1p1: Line is truncated:
```

full logs: https://paste.fedoraproject.org/paste/j4EIRN6d60pcreH4X8Ejxg/raw

**Comment by vasukulkarni** [comment] 2017-07-07 01:24
test run log for my reference: http://qa-proxy.ceph.com/teuthology/vasu-2017-07-06_21:11:48-ceph-ansible-master-distro-basic-smithi/1368385/teuthology.log

**Comment by djgalloway** [comment] 2017-07-07 16:36
`ceph-disk activate` fails because `ceph-disk prepare` is never called.  All the tasks in `roles/ceph-osd/tasks/scenarios/journal_collocation.yml` are getting skipped.  Trying to track down why,

**Comment by vasukulkarni** [comment] 2017-07-07 22:19
@djgalloway with wip-dgalloway-debug run here: http://qa-proxy.ceph.com/teuthology/vasu-2017-07-07_18:25:04-ceph-ansible-master-distro-basic-smithi/1371982/teuthology.log

**Comment by djgalloway** [comment] 2017-07-10 14:05
@vasukulkarni You'll have to rerun.  The ansible run failed for a different reason before it got to the OSD provisioning tasks.

**Comment by vasukulkarni** [comment] 2017-07-10 20:46
@djgalloway how about this one? http://qa-proxy.ceph.com/teuthology/vasu-2017-07-10_20:14:10-ceph-ansible-master-distro-basic-smithi/1383604/teuthology.log

**Comment by djgalloway** [comment] 2017-07-10 22:00
So as best I can tell, https://github.com/ceph/ceph-ansible/blob/f75d36ce189bd0395920fc2b4af20512af1776e2/roles/ceph-osd/tasks/check_devices_static.yml#L2 gets called and this gets populated

```
TASK [ceph-osd : debug] ********************************************************
task path: /home/ubuntu/ceph-ansible/roles/ceph-osd/tasks/check_devices_static.yml:10
ok: [smithi021.front.sepia.ceph.com] => {
    "ispartition_results": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "cmd": "readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                "delta": "0:00:00.004242",
                "end": "2017-07-10 20:41:36.466866",
                "failed": false,
                "failed_when_result": false,
                "invocation": {
                    "module_args": {
                        "_raw_params": "readlink -f /dev/nvme0n1p1 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                        "_uses_shell": true,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "warn": true
                    },
                    "module_name": "command"
                },
                "item": "/dev/nvme0n1p1",
                "rc": 0,
                "start": "2017-07-10 20:41:36.462624",
                "stderr": "",
                "stdout": "/dev/nvme0n1p1",
                "stdout_lines": [
                    "/dev/nvme0n1p1"
                ],
                "warnings": []
            },
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "cmd": "readlink -f /dev/nvme0n1p2 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                "delta": "0:00:00.004028",
                "end": "2017-07-10 20:41:36.781237",
                "failed": false,
                "failed_when_result": false,
                "invocation": {
                    "module_args": {
                        "_raw_params": "readlink -f /dev/nvme0n1p2 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                        "_uses_shell": true,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "warn": true
                    },
                    "module_name": "command"
                },
                "item": "/dev/nvme0n1p2",
                "rc": 0,
                "start": "2017-07-10 20:41:36.777209",
                "stderr": "",
                "stdout": "/dev/nvme0n1p2",
                "stdout_lines": [
                    "/dev/nvme0n1p2"
                ],
                "warnings": []
            },
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "cmd": "readlink -f /dev/nvme0n1p3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                "delta": "0:00:00.004397",
                "end": "2017-07-10 20:41:37.281342",
                "failed": false,
                "failed_when_result": false,
                "invocation": {
                    "module_args": {
                        "_raw_params": "readlink -f /dev/nvme0n1p3 | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}|fio[a-z]{1,2}[0-9]{1,2}$'",
                        "_uses_shell": true,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "warn": true
                    },
                    "module_name": "command"
                },
                "item": "/dev/nvme0n1p3",
                "rc": 0,
                "start": "2017-07-10 20:41:37.276945",
                "stderr": "",
                "stdout": "/dev/nvme0n1p3",
                "stdout_lines": [
                    "/dev/nvme0n1p3"
                ],
                "warnings": []
            }
        ]
    }
}
```

Which is good.  Then this **should** get called, I think: https://github.com/ceph/ceph-ansible/blob/f75d36ce189bd0395920fc2b4af20512af1776e2/roles/ceph-osd/tasks/scenarios/journal_collocation.yml#L24

But `parted_results` is never populated so the task is skipped and the partition is never `ceph-disk prepare`d because https://github.com/ceph/ceph-ansible/blob/f75d36ce189bd0395920fc2b4af20512af1776e2/roles/ceph-osd/tasks/check_devices_static.yml#L36 is skipped.

So `ceph-disk activate` later fails because the partition is never prepared by ceph-disk and there's no filesystem on the partition.

**Comment by djgalloway** [comment] 2017-07-11 17:07
@guits seems to know what the problem is here and may be resolving it in https://github.com/ceph/ceph-ansible/pull/1656

**Comment by vasukulkarni** [comment] 2017-07-12 16:48
@guits once this is merged I can rerun on master, https://github.com/ceph/ceph-ansible/issues/1660 , Need that commit to rerun.

**Comment by guits** [comment] 2017-07-12 18:40
@vasukulkarni the PR has been merged

**Comment by vasukulkarni** [comment] 2017-07-12 19:06
@guits thanks, I will pick up master and update the results here.

**Comment by vasukulkarni** [comment] 2017-07-14 15:32
Seeing this now with latest master: https://paste.fedoraproject.org/paste/qRX91NeIibtiBcZ9de96Sg/raw

**Comment by guits** [comment] 2017-07-20 13:36
@vasukulkarni can you provides the group_vars/* ?

**Comment by guits** [comment] 2017-07-20 13:49
@vasukulkarni after having analyzed the last log you provided I have found that early in the deployment there was a failure:
```
2017-07-13T00:35:34.822 INFO:teuthology.orchestra.run.smithi136.stdout:Unable to start service ceph-mon@smithi136: Job for ceph-mon@smithi136.service failed because start of the service was attempted too often. See "systemctl status ceph-mon@smithi136.service" and "journalctl -xe" for details.
2017-07-13T00:35:34.822 INFO:teuthology.orchestra.run.smithi136.stdout:To force a start use "systemctl reset-failed ceph-mon@smithi136.service" followed by "systemctl start ceph-mon@smithi136.service" again.
```

The monitor service on this node (`smithi136`) is the last mon in your monitors group.
Since this node got a failure, the playbook continue to run but ignoring smithi136.

The task which fetch the mgr key is normally executed on the last mon, but it didn't happen since this node has been pulled out from the monitor group. Therefore, the task which is supposed to copy the mgr key from ansible node to mgr node has failed.

You already reported an issue with the last error on a mon not long ago.
I suspect this is something related to your lab environment since I have never been able to reproduce this issue.

**Comment by leseb** [comment] 2017-07-25 12:05
Closing this due to inactivity, feel free to re-open.

**Closed by leseb** 2017-07-25 12:05 UTC
