### ISSUE TITLE
Grafana Dashboard not available on public IP port 3000

### ISSUE THREAD

**Issue by SayidHosseini** [ceph/ceph-ansible#4416] opened 2019-09-02 18:24 UTC
**Bug Report**

What happened:
Following the instruction [here](https://docs.ceph.com/ceph-ansible/master/) on Ceph-Ansible Installation. I successfully deployed a three-node cluster of Ceph. The output of the ansible-playbook command was with failed=0. However the dashboard is not available externally; meaning that the incoming requests on port 3000 are not forwarded to the docker container. Although the service is fully functional internally. But for example Prometheus is available through port 9090 externally.

What you expected to happen:
To have the grafana dashboard available externally at port 3000.

How to reproduce it (minimal and precise):

Install nautilus from stable-4.0 with Dashboard enabled.

Share your group_vars files, inventory
group_vars:
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus 
public_network: "192.168.56.0/24"
cluster_network: "192.168.56.0/24"
monitor_interface: ens224
```

inventory:
```
[mons]
cephansible1
cephansible2
cephansible3

[osds]
cephansible1
cephansible2
cephansible3

[grafana-server]
cephansible1
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7 1810
* Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
* Docker version if applicable (e.g. `docker version`):  Docker version 1.13.1, build 7f2769b/1.13.1
* Ansible version (e.g. `ansible-playbook --version`):  ansible-playbook 2.8.4
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)

**Comment by dsavineau** [comment] 2019-09-03 13:11
Could you share your ansible logs ?

**Comment by SayidHosseini** [comment] 2019-09-04 11:47
Sure!
Here you go:
[ansible.log](https://github.com/ceph/ceph-ansible/files/3574345/ansible.log)

**Comment by dsavineau** [comment] 2019-09-04 13:30
> However the dashboard is not available externally; meaning that the incoming requests on port 3000 are not forwarded to the docker container

What do you mean exactly by externally ? because we don't use NAT for the container so there's no forward, they're using the host network.
Do you have something listening on port 3000 on `cephansible1` node ?
If not, could you check the grafana container logs ?

```console
# docker logs grafana-server
and/or
# journalctl -u grafana-server
```

**Comment by SayidHosseini** [comment] 2019-09-04 14:13
I mean there is no service listening on port 3000 on `public_network` IP range, though when I get the list of listening ports, there is one listening on 3000 but with a specific network to containers (the IP is 172.17.0.1:3000). Here is the output of `ss -lntu` command([ListeningPorts.txt](https://github.com/ceph/ceph-ansible/files/3574847/ListeningPorts.txt))
Here are the logs for grafana-server([grafana-server-logs.txt](https://github.com/ceph/ceph-ansible/files/3574881/grafana-server-logs.txt))

I could manually stop the container using docker cli and start it again with the port forwarding (like `docker run -d -p 3000:3000 grafana/grafana`) but this does not seem to be a descent solution!

Also, note that after a reboot of the `cephansible1` machine, the grafana container didn't start automatically!

**Comment by dsavineau** [comment] 2019-09-04 14:27
> mean there is no service listening on port 3000 on `public_network` IP range, though when I get the list of listening ports, there is one listening on 3000 but with a specific network to containers (the IP is 172.17.0.1:3000). Here is the output of `ss -lntu` command([ListeningPorts.txt](https://github.com/ceph/ceph-ansible/files/3574847/ListeningPorts.txt))
> Here are the logs for grafana-server([grafana-server-logs.txt](https://github.com/ceph/ceph-ansible/files/3574881/grafana-server-logs.txt))

Weird because we explicitly configure grafana on the `public_network` [1]. Could you run the playbook with more verbosity (-vv) because in the current logs I couldn't see the fact values.

> I could manually stop the container using docker cli and start it again with the port forwarding (like `docker run -d -p 3000:3000 grafana/grafana`) but this does not seem to be a descent solution!

Again you don't need port forwarding because we're using the host network configuration [2]

> Also, note that after a reboot of the `cephansible1` machine, the grafana container didn't start automatically!

That's supposed to be done by [3]

[1] https://github.com/ceph/ceph-ansible/blob/stable-4.0/roles/ceph-facts/tasks/facts.yml#L316
[2] https://github.com/ceph/ceph-ansible/blob/stable-4.0/roles/ceph-grafana/templates/grafana-server.service.j2#L18
[3] https://github.com/ceph/ceph-ansible/blob/stable-4.0/roles/ceph-grafana/tasks/setup_container.yml#L25

**Comment by SayidHosseini** [comment] 2019-09-04 14:40
Thank you for your quick reply!

> Again you don't need port forwarding because we're using the host network configuration [2]

I got you the first time. I meant that as a workaround; certainly not a solution

> That's supposed to be done by [3]

That's true, but it didn't work

Here is the verbose log([ansible.log](https://github.com/ceph/ceph-ansible/files/3575015/ansible.log))

**Comment by dsavineau** [comment] 2019-09-04 15:03
```console
2019-09-04 19:02:21,098 p=147571 u=root |  TASK [ceph-facts : set grafana_server_addr fact - ipv4] *********************************************************************************************************************************************************
2019-09-04 19:02:21,099 p=147571 u=root |  task path: /usr/share/ceph-ansible/roles/ceph-facts/tasks/facts.yml:314
2019-09-04 19:02:21,099 p=147571 u=root |  Wednesday 04 September 2019  19:02:21 +0430 (0:00:00.203)       0:02:58.674 *** 
2019-09-04 19:02:21,242 p=147571 u=root |  ok: [cephansible1] => changed=false 
  ansible_facts:
    grafana_server_addr: 192.168.56.234
(...)
2019-09-04 19:03:42,851 p=147571 u=root |  TASK [ceph-facts : set grafana_server_addr fact - ipv4] *********************************************************************************************************************************************************
2019-09-04 19:03:42,851 p=147571 u=root |  task path: /usr/share/ceph-ansible/roles/ceph-facts/tasks/facts.yml:314
2019-09-04 19:03:42,852 p=147571 u=root |  Wednesday 04 September 2019  19:03:42 +0430 (0:00:00.344)       0:04:20.427 *** 
2019-09-04 19:03:43,096 p=147571 u=root |  ok: [cephansible1] => changed=false 
  ansible_facts:
    grafana_server_addr: 172.17.0.1
```

That's very strange. The grafana ip address fact changed during the playbook execution.
172.17.0.1 is part of the docker interal network ?
Do you have anything configured related to grafana ?

**Comment by SayidHosseini** [comment] 2019-09-04 15:11
No, this has been executed on a clean install of CentOS.

**Comment by dsavineau** [comment] 2019-09-04 15:39
Ok so according to the logs, `grafana_server_addr: 172.17.0.1` seems to be set during the `infrastructure-playbooks/dashboard.yml` playbook execution.
My theory is that somehow (I'm not able to reproduce on my side for now) `public_network ` value is lost when this playbook is executed so it fallbacks to the default value `0.0.0.0/0`.
Because the docker network appears before the `public_network` in the ansible facts then the ipaddr filter get all ip addresses and returns the first one.
If you run :
```console
$ ansible -i hosts all -b -m setup -a 'filter=ansible_all_ipv4_addresses'
xxxxx | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.17.0.1",
            "192.168.100.10"
        ]
    },
    "changed": false
}
```
You should have this kind of output.
But even with this I don't have the same behavious.

Did you define `public_network` in `group_vars/all.yml` ?
If yes could you try to add this task to `roles/ceph-facts/tasks/facts.yml` just before the `set grafana_server_addr fact - ipv4` task (~ L314) :

```yaml
- debug:
    msg: '{{ public_network }}'
```

**Comment by SayidHosseini** [comment] 2019-09-14 15:50
So after a *lot* of investigation, while reading the **`Ceph Cookbook 2nd edition - Packt Publication`**, I came across a section regarding `grafana-server`:

> If you are running ansible-playbook on a host mentioned in the inventory file, you will need to append **`ansible_connection=local`** to each line in the inventory file that mentions that host.

**I was actually installing Ceph from `cephansible1` node!**

So I started installing Ceph from the beginning (on a fresh install - rerunning on the previous installation wouldn't work) with a change to the inventory file:

```
[mons]
cephansible1 ansible_connection=local
cephansible2
cephansible3

[osds]
cephansible1 ansible_connection=local
cephansible2
cephansible3

[grafana-server]
cephansible1 ansible_connection=local
```

And fortunately that fixed it.

@dsavineau I'm not sure if this needs to be documented so I won't close it.

**Comment by dsavineau** [comment] 2019-09-18 17:24
Ok so we can close it

**Closed by dsavineau** 2019-09-18 17:24 UTC
Labels: needs info
