### ISSUE TITLE
4.0-rc4 IndexError: list index out of range

### ISSUE THREAD

**Issue by cloudguy23** [ceph/ceph-ansible#3925] opened 2019-04-28 15:16 UTC
**Bug Report**

What happened:
Upgraded to v4.0-rc4, transposed group_var/*.yml overrides from 4.0rc3.   Unable to apply 4.0rc4 site.yml against rc3 deployed cluster.

Somewhat related to #3921 

```
ansible-playbook -i ../hosts site.yml -vvv 
...
task path: /opt/playbooks/ceph/ceph-ansible-4.0.0rc4/roles/ceph-validate/tasks/main.yml:2
Sunday 28 April 2019  10:47:14 -0400 (0:00:02.587)       0:02:48.741 ********** 
ok: [mon01s.domain.local] => changed=false
ok: [mon02s.domain.local] => changed=false
ok: [mon03s.domain.local] => changed=false
ok: [objgw01s.domain.local] => changed=false
ok: [objgw02s.domain.local] => changed=false
fatal: [osd23s.domain.local]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/playbooks/ceph/ceph-ansible-4.0.0rc4/plugins/actions/validate.py", line 110, in run
    host, error.path[0])
IndexError: list index out of range

... repeats for all OSD hosts ...
```

Relevant overrides applicable to rc4 changed osd / scenario defaults include:

all.yml:
osd_objectstore: bluestore

osds.yml:
osd_auto_discovery: true
dmcrypt: true

in rc3 I also had to manually specify LVM scenario.

What you expected to happen:
Playbook to execute successfully.
How to reproduce it (minimal and precise):
* upgrade group_vars (manually transpose overrides from rc3 group_vars)
* Run `ansible-playbook -i ../hosts site.yml -vvv`

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.7.10
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0rc4
* Ceph version (e.g. `ceph -v`): 14.2.0

**Comment by dsavineau** [comment] 2019-04-29 15:36
I think this is a duplicate of https://github.com/ceph/ceph-ansible/issues/3878

**Comment by cloudguy23** [comment] 2019-04-29 15:39
> I think this is a duplicate of #3878

Similar symptom, affects 4.0 branch, simply re-running playbook without changes from rc3.

**Comment by dsavineau** [comment] 2019-04-29 15:43
btw rc3 should have the same issue.
This should be fixed by https://github.com/ceph/ceph-ansible/pull/3899

**Comment by cloudguy23** [comment] 2019-05-04 15:36
I upgraded to rc5, same issue.   Running with --check:

```
TASK [ceph-facts : set_fact osd_pool_default_crush_rule] ****************************************************
task path: /opt/playbooks/ceph/ceph-ansible-4.0.0rc5/roles/ceph-facts/tasks/facts.yml:274
Saturday 04 May 2019  11:35:11 -0400 (0:00:00.778)       0:00:31.164 ********** 
fatal: [mon01.domain.local]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'rc'
    The error appears to have been in '/opt/playbooks/ceph/ceph-ansible-4.0.0rc5/roles/ceph-facts/tasks/facts.yml': line 274, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_crush_rule
      ^ here
fatal: [stor23.domain.local]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'rc'
  
    The error appears to have been in '/opt/playbooks/ceph/ceph-ansible-4.0.0rc5/roles/ceph-facts/tasks/facts.yml': line 274, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_crush_rule
      ^ here
```

Building the cluster with rc3 didn't populate `osd pool default crush rule` in ceph.conf.

What's the ceph-ansible way of getting around this?

**Comment by dsavineau** [comment] 2019-05-06 15:00
The check mode issue isn't related to the original issue.
We known that currently the ansible check mode isn't working but I think https://github.com/ceph/ceph-ansible/pull/3934 can fix some of them.

**Comment by cloudguy23** [comment] 2019-05-24 21:58
I tried with rc8, same resutls
```
TASK [ceph-validate : validate provided configuration] **********************************************************************
task path: /opt/playbooks/ceph/ceph-ansible-4.0.0rc8/roles/ceph-validate/tasks/main.yml:2
Friday 24 May 2019  17:49:33 -0400 (0:00:01.641)       0:02:25.929 ************ 
ok: [mon02s.local.domain] => changed=false
ok: [mon01s.local.domain] => changed=false
ok: [mon03s.local.domain] => changed=false
ok: [objgw01s.local.domain] => changed=false
ok: [objgw02s.local.domain] => changed=false
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 648, in _execute
    result = self._handler.run(task_vars=variables)
  File "/opt/playbooks/ceph/ceph-ansible-4.0.0rc8/plugins/actions/validate.py", line 110, in run
    host, error.path[0])
IndexError: list index out of range

fatal: [osd23s.local.domain]: FAILED! => 
  msg: Unexpected failure during module execution.
```

Any idea how I may troubleshoot this?

**Comment by neonardo1** [comment] 2019-05-30 21:40
I'm in the same boat on this one.

```
TASK [ceph-validate : validate provided configuration] ************************************************************************************************************************************************************************************************************************
task path: /root/ansible/ceph-ansible/roles/ceph-validate/tasks/main.yml:2
Thursday 30 May 2019  16:38:39 -0500 (0:00:00.114)       0:01:04.904 **********
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 648, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/ceph-ansible/plugins/actions/validate.py", line 110, in run
    host, error.path[0])
IndexError: list index out of range

fatal: [ssd-storage02-tx]: FAILED! =>
  msg: Unexpected failure during module execution.
  stdout: ''
```

**Comment by wesleysutton** [comment] 2019-06-10 13:49
I had the same error on both stable-3.2 and stable-4.0. Here's the hack/fix:

```
diff --git a/plugins/actions/validate.py b/plugins/actions/validate.py
index 79fc941..1c76a59 100644
--- a/plugins/actions/validate.py
+++ b/plugins/actions/validate.py
@@ -100,7 +100,8 @@ class ActionModule(ActionBase):
 
         except Invalid as error:
             display.vvvv("Notario Failure: %s" % str(error))
-            msg = "[{}] Validation failed for variable: {}".format(host, error.path[0])
+            given = ""
+            msg = "[{}] Validation failed for variable: {}".format(host, error)
             display.error(msg)
             reason = "[{}] Reason: {}".format(host, error.reason)
             try:
```

**Closed** 2019-10-08 00:59 UTC
Labels: wontfix
