### ISSUE TITLE
crash if libselinux-python is not installed.

### ISSUE THREAD

**Issue by mmgaggle** [ceph/ceph-ansible#903] opened 2016-07-25 21:10 UTC
Initial setup fails if libselinux-python is not installed:

```
TASK [ceph.ceph-common : apply operating system tuning] ************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{os_tuning_params}}').
This feature
will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [top] (item={u'name': u'kernel.pid_max', u'value': 4194303}) => {"failed": true, "item": {"name": "kernel.pid_max", "value": 4194303}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [top] (item={u'name': u'fs.file-max', u'value': 26234859}) => {"failed": true, "item": {"name": "fs.file-max", "value": 26234859}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [top] (item={u'name': u'vm.zone_reclaim_mode', u'value': 0}) => {"failed": true, "item": {"name": "vm.zone_reclaim_mode", "value": 0}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [top] (item={u'name': u'vm.vfs_cache_pressure', u'value': 50}) => {"failed": true, "item": {"name": "vm.vfs_cache_pressure", "value": 50}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [top] (item={u'name': u'vm.swappiness', u'value': 10}) => {"failed": true, "item": {"name": "vm.swappiness", "value": 10}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [top] (item={u'name': u'vm.min_free_kbytes', u'value': 67584}) => {"failed": true, "item": {"name": "vm.min_free_kbytes", "value": 67584}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
	to retry, use: --limit @site.yml.retry

PLAY RECAP *********************************************************************
top                        : ok=8    changed=0    unreachable=0    failed=1
```

**Comment by chengweiv5** [comment] 2016-07-26 00:58
I think this is normal, which is needed by ansible.

**Comment by leseb** [comment] 2016-07-26 09:12
Thanks for reporting this @mmgaggle I'll update the dependancies.

**Comment by leseb** [comment] 2016-07-26 09:13
This is actually a dependancy for CentOS installations. Are you trying on RHEL?

**Comment by leseb** [comment] 2016-08-10 09:59
Closing this, feel free to re-open if the issue is not solved.

**Closed by leseb** 2016-08-10 09:59 UTC
