### ISSUE TITLE
OSD on Debian Jessie : No cluster conf found

### ISSUE THREAD

**Issue by HanXHX** [ceph/ceph-ansible#406] opened 2015-09-17 07:18 UTC
Hi,

I try your playbook on Debian Jessie (packages from Debian). On OSD, it seems we have a bug:

```
# systemctl status ceph
● ceph.service - LSB: Start Ceph distributed file system daemons at boot time
   Loaded: loaded (/etc/init.d/ceph)
   Active: active (exited) since Wed 2015-09-16 18:22:08 CEST; 14h ago

Sep 16 18:22:08 ceph-osd0 ceph[665]: ERROR:ceph-disk:Failed to activate
Sep 16 18:22:08 ceph-osd0 ceph[665]: ceph-disk: Error: No cluster conf found in /etc/ceph with fsid 00000000-0000-0000-0000-000000000000
Sep 16 18:22:08 ceph-osd0 ceph[665]: ERROR:ceph-disk:Failed to activate
Sep 16 18:22:08 ceph-osd0 ceph[665]: ceph-disk: Error: No cluster conf found in /etc/ceph with fsid 00000000-0000-0000-0000-000000000000
Sep 16 18:22:08 ceph-osd0 ceph[665]: ceph-disk: Error: One or more partitions failed to activate
```
I tried with debian kernels:
- 4.1.0-0.bpo.2-amd64
- 3.16.0-4-amd64

On Mon:
```
# ceph -s
    cluster 4a158d27-f750-41d5-9e7f-26ce4c9d2d45
     health HEALTH_ERR 192 pgs stuck inactive; 192 pgs stuck unclean; no osds
     monmap e1: 2 mons at {ceph-mon0=192.168.239.10:6789/0,ceph-mon1=192.168.239.11:6789/0}, election epoch 6, quorum 0,1 ceph-mon0,ceph-mon1
     osdmap e1: 0 osds: 0 up, 0 in
      pgmap v2: 192 pgs, 3 pools, 0 bytes data, 0 objects
            0 kB used, 0 kB / 0 kB avail
                 192 creating
```

Vagrant variables:
```
---

mon_vms: 2
osd_vms: 2
mds_vms: 1
rgw_vms: 0
client_vms: 1

subnet: 192.168.239

memory: 256

vagrant_box: deb/jessie-amd64
vagrant_storagectl: 'SATA Controller'
```

Ansible vars:
```
#
# ceph-common
#

ceph_origin: 'distro'
ceph_use_distro_backport: true
cephx_require_signatures: false # pour utiliser rbd
# $ uuidgen
fsid: '65f3121b-fbcc-4478-919a-95aa4dc0ddab'
debian_package_dependencies:
  - python-pycurl
  - hdparm
```

Cheers!

Emilien

**Comment by leseb** [comment] 2015-09-17 08:31
I haven't tested this on Debian for a while, let me try to reproduce this with Vagrant.

**Comment by leseb** [comment] 2015-09-17 09:58
I can reproduce this, looks like there is a problem with ceph-disk (possibly the 0.80.7 version) during the prepare sequence, investigating a bit.

**Comment by leseb** [comment] 2015-09-17 14:00
Found the root cause, the prepare step has:

```/usr/bin/ceph-conf --cluster=None --name=osd. --lookup osd_mkfs_options_xfs````

And uses `--cluster=None` which is wrong.
If you can have a look at that I'll be nice. I don't have much time at the moment.

Can you try with thceph repo?

**Comment by leseb** [comment] 2015-10-16 22:36
Closing this for now, feel free to reopen.

**Closed by leseb** 2015-10-16 22:36 UTC
