### ISSUE TITLE
ceph-mon : collect admin and bootstrap keys failed

### ISSUE THREAD

**Issue by like-inspur** [ceph/ceph-ansible#2411] opened 2018-02-22 08:59 UTC
I try to install ceph-ansible-3.0.24 on three centos 7.3 nodes，ansible version is 2.4.2.0, ceph version is luminous. I config monitor_secret from monitor_keys_example file. I also config correct monitor_interface and public_network and cluster_network. Three nodes config hosts like this:
[mons]
ceph-108
ceph-109
ceph-110

[osds]
ceph-108
ceph-109
ceph-110

[mdss]
ceph-108
ceph-109
ceph-110

[mgrs]
ceph-108
ceph-109
ceph-110

The ansible output of this task is like this:
TASK [ceph-mon : collect admin and bootstrap keys] **********************************************************************************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead.. This feature will be removed in version 2.4. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead.. This feature will be removed in version 2.4. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead.. This feature will be removed in version 2.4. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [ceph-108]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-108", "-t", "30"], "delta": "0:00:33.414343", "end": "2018-02-22 16:58:00.678064", "msg": "non-zero return code", "rc": 1, "start": "2018-02-22 16:57:27.263721", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}
fatal: [ceph-109]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-109", "-t", "30"], "delta": "0:00:33.929236", "end": "2018-02-22 16:58:01.219484", "msg": "non-zero return code", "rc": 1, "start": "2018-02-22 16:57:27.290248", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}
fatal: [ceph-110]: FAILED! => {"changed": false, "cmd": ["ceph-create-keys", "--cluster", "ceph", "-i", "ceph-110", "-t", "30"], "delta": "0:00:33.923618", "end": "2018-02-22 16:58:01.200801", "msg": "non-zero return code", "rc": 1, "start": "2018-02-22 16:57:27.277183", "stderr": "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nINFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'\nceph-mon was not able to join quorum within 0 seconds", "stderr_lines": ["INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'", "ceph-mon was not able to join quorum within 0 seconds"], "stdout": "", "stdout_lines": []}

**Comment by leseb** [comment] 2018-02-23 14:21
group_vars files + generated ceph.conf please

**Comment by like-inspur** [comment] 2018-02-24 01:57
[root@ceph-108 ceph-ansible-3.0.24]# cat /etc/ceph/ceph.conf 
[global]
rbd_default_features = 1
fsid = 521ec202-1d94-4d7f-8f36-1922a53ea815
mon initial members = ceph-108,ceph-109,ceph-110
mon host = 10.110.17.108,10.110.17.109,10.110.17.110
public network = 10.0.17.0/24
cluster network = 10.0.17.0/24

[osd]
osd mkfs type = xfs
osd mkfs options xfs = -f -i size=2048
osd mount options xfs = noatime,largeio,inode64,swalloc
osd journal size = 5120

[mds.ceph-108]
host = ceph-108
[mds.ceph-109]
host = ceph-109
[mds.ceph-110]
host = ceph-110

group_vars files are too large, the main config of all.yml and mons.yml is like this:
generate_fsid: true
monitor_interface: ens192
public_network: 10.0.17.0/24
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
monitor_secret: AQBQn8tUiII8JxAASRfxOvzrTKKoR9HK37JYsQ==

**Comment by dlbewley** [comment] 2018-02-27 22:07
Same problem on RHEL 7.4.

- *ceph.conf*

```
[root@ceph-mon-01 ~]# grep -v -E '^$' /etc/ceph/ceph.conf
# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
fsid = 24903ef2-1df0-4592-a05a-9e722c3fa09e
mon initial members = ceph-mon-01,ceph-mon-02,ceph-mon-03
mon host = 172.23.22.200,172.23.22.201,172.23.22.202
public network = 172.23.22.0/24
cluster network = 172.23.23.0/24
```

- *Group Vars*

```
[ceph-admin@ceph-admin group_vars]$ grep -v -E '^#|^$' *
admin:---
admin:ceph_admin_user_generate_ssh_key: True
admin:ceph_repos:
admin:  - rhel-7-server-rpms
admin:  - rhel-7-server-extras-rpms
admin:  - rhel-7-server-rhceph-3-tools-rpms
all:---
all:satellite_client_activation_key: openstack-ceph
all:ceph_admin_user: ceph-admin
all:ceph_admin_group: ceph-admin
all:ceph_admin_user_uid: 6386
all:ceph_admin_user_gid: 2226
all:ceph_admin_user_home: "/home/{{ ceph_admin_user }}"
all:ceph_admin_user_generate_ssh_key: False
all:ceph_admin_user_pass: "$6$Na1xxxxGknFw/n8hGsbFcISWk/xR6jLbjmg1L1"
all:ceph_sysctl:
all:  kernel.pid_max: 4194303
all:ceph_network_cluster_cidr: 172.23.22.0/24
all:ceph_network_public_cidr: 172.23.23.0/24
all:dummy:
all:fetch_directory: ~/ceph-ansible-keys
all:ceph_repository_type: "cdn"
all:ceph_origin: repository
all:ceph_repository: rhcs
all:ceph_rhcs_version: "3"
all:monitor_address_block: "172.23.22.0/24"
all:ip_version: ipv4
all:public_network: "172.23.22.0/24"
all:cluster_network: "172.23.23.0/24"
mons:---
mons:ceph_repos:
mons:  - rhel-7-server-rpms
mons:  - rhel-7-server-extras-rpms
mons:  - rhel-7-server-rhceph-3-mon-rpms
mons:  # only for rados
mons:  - rhel-7-server-rhceph-3-tools-rpms
mons:network_aggregates:
mons:  - name: team0
mons:    conn_name: public
mons:    type: team
mons:    mtu: 9214
mons:    config:
mons:      runner:
mons:        name: lacp
mons:    slaves:
mons:      - em1
mons:      - em2
mons:dummy:
osds:---
osds:ceph_repos:
osds:  - rhel-7-server-rpms
osds:  - rhel-7-server-extras-rpms
osds:  - rhel-7-server-rhceph-3-osd-rpms
osds:  # only for rados
osds:  - rhel-7-server-rhceph-3-tools-rpms
osds:network_aggregates:
osds:  - name: team0
osds:    conn_name: public
osds:    type: team
osds:    mtu: 9214
osds:    config:
osds:      runner:
osds:        name: lacp
osds:    slaves:
osds:      - p2p1
osds:      - p2p2
osds:  - name: team1
osds:    conn_name: cluster
osds:    type: team
osds:    mtu: 9214
osds:    config:
osds:      runner:
osds:        name: lacp
osds:    slaves:
osds:      - p3p1
osds:      - p3p2
osds:dummy:
osds:osd_scenario: "non-collocated"
osds:devices:
osds:   - /dev/sda
osds:   - /dev/sdb
osds:   - /dev/sdc
osds:   - /dev/sdd
osds:   - /dev/sde
osds:   - /dev/sdf
osds:   - /dev/sdg
osds:   - /dev/sdh
osds:   - /dev/sdi
osds:   - /dev/sdj
osds:   - /dev/sdk
osds:   - /dev/sdl
osds:   - /dev/sdm
osds:   - /dev/sdn
osds:dedicated_devices:
osds:   - /dev/nvme0n1
```

**Comment by dlbewley** [comment] 2018-02-28 04:07
Embarrassingly, this turned out to be caused by firewalld in my case.

**Comment by like-inspur** [comment] 2018-02-28 07:35
I have disable firewalld and selinux, but problem still exists.  @leseb @dlbewley @hunter @gbraad @dang

**Comment by leseb** [comment] 2018-02-28 11:52
@like-inspur public_network is set to 10.0.17.0/24 and mon_host is 10.110.17.108, is this expected? Did you check mon logs?

**Comment by like-inspur** [comment] 2018-03-01 00:51
I have two network cards on every host, this config works fine with ceph version kraken by ceph-ansible v2.3.0 . I don't know why doesn't work on this verison. The output of mon log is only mon.ceph-108@0(probing).data_health(0) update_stats avail 88% total 13706 MB, used 1542 MB, avail 12163 MB

**Comment by dlbewley** [comment] 2018-03-02 21:30
@like-inspur 

```
mon initial members = ceph-108,ceph-109,ceph-110
mon host = 10.110.17.108,10.110.17.109,10.110.17.110
public network = 10.0.17.0/24
cluster network = 10.0.17.0/24
```

I believe your believe your mon hosts should be on _public network_. Can your OSD hosts reach port 6789 on 10.110.17.108,10.110.17.109,10.110.17.110 from their _public network_ interface?

Can you post an `ip -o a` and `ip route ls` from each?

**Comment by likerj** [comment] 2018-03-05 03:00
6789 is listening on addresses of public network. I config 10.110.17.0/24 for public network, then the installation is correct.  After installation I found there are only two pools for cephfs（1 cephfs_data and 2cephfs_metada），but the rbd pool for ceph rbd doesn't exsits. @leseb  @dlbewley

**Comment by leseb** [comment] 2018-03-05 12:46
@likerj the rbd pool does not exist anymore as of Luminous.
I'm closing this, assuming everything is solved.

Feel free to re-open if you have any concerns, thanks.

**Closed by leseb** 2018-03-05 12:46 UTC

**Comment by satishdotpatel** [comment] 2018-07-12 04:21
I need urgent help and this is really big issue look like, If i put monitor_address_block & public_network on same subnet then i am getting error "No first item, sequence was empty" and if i put them on different subnet then get above error "ceph-mon was not able to join quorum" 

I am running openstack-ansible and i want my public_network on br-storage vlan, Please advice

monitor_address_block: "192.168.100.0/24"
public_network: "172.16.200.0/24"
cluster_network: "10.5.1.0/24"
