### ISSUE TITLE
Vagrant deployment on Virtualbox is failing with error: undefined monitor_interface

### ISSUE THREAD

**Issue by jsaintrocc** [ceph/ceph-ansible#702] opened 2016-04-09 21:56 UTC
When using `master` and following the procedure in the top-level README.md, Vagrant is failing with the following error:

```
TASK: [ceph.ceph-common | generate ceph configuration file] *******************
fatal: [mon1] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'
fatal: [mon2] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'
fatal: [mon0] => One or more undefined variables: 'dict object' has no attribute 'monitor_interface'

FATAL: all hosts have already failed -- aborting
```

Everything works as expected when using `ceph-ansible-1.0.3`.

**Comment by leseb** [comment] 2016-04-10 14:34
Hum, what's the value for https://github.com/ceph/ceph-ansible/blob/master/vagrant_variables.yml.sample#L26?

**Comment by jsaintrocc** [comment] 2016-04-10 18:06
Same value as default `eth: 'eth1'`.  I'm testing by going though the commits following the 1.0.3 tag.  Using the next commit `d7d83273e71bff211d01efa90bbc3a3e7c57e0b8` I get `'mon_containerized_deployment_with_kv' is undefined`.  I'm using Ansible 1.9.4 and Virtualbox 5.0.16 on OS X.  What versions are you testing with Sebastien?

**Comment by leseb** [comment] 2016-04-10 21:29
Weird `mon_containerized_deployment_with_kv` is defined here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L339, this issue was fixed in #653

**Comment by jsaintrocc** [comment] 2016-04-10 23:21
Ah the Ansible version is the key.  I switched to Ansible 2.0.1.0 and everything works as expected (using master).  Then I confirmed it breaks again when I switch to Ansible 1.9.5.    I used Virtualenv and it made it pretty easy to switch between Ansible versions.  So is backwards compatibility to Ansible 1.9.X important?

**Comment by leseb** [comment] 2016-04-11 08:43
Well it is yes, I just don't get the error. I'll try to build an env with `1.9.4`.
This is something we need to solve in our CI too.

@andrewschoen any chance to give a try to this? Testing the playbook on `1.9.4` and `2.0.0.2` on both CentOS and Ubuntu. Let me know if I can give you a hand on this.

**Comment by leseb** [comment] 2016-04-11 09:00
@jsaintrocc I just bootstrapped a Ceph cluster on a single machine with 1 mon and 2 osds without using Vagrant (shouldn't be a problem) using Ansible `1.9.4`. I can't reproduce your problem... :/

**Closed** 2016-04-12 10:09 UTC
