### ISSUE TITLE
ceph-ansible keeps creating a single OSD from multiple disks in Octopus

### ISSUE THREAD

**Issue by ExpatZ** [ceph/ceph-ansible#5727] opened 2020-09-04 15:52 UTC
Hi, I have been running across an issue where I have one or two OSD nodes making one big lvm out of multiple disks instead of a osd on each, it is random which machine does it each run and running it against a single machine to fix it after rebuilding it from scratch may or may not correct the problem.

How do I force it to use individual disks for each OSD?
This is only a problem since LVM was introduced as the main partioning mechanism in Luminous for us.

**Comment by dsavineau** [comment] 2020-09-04 18:14
Please share the full ansible log file, inventory and variables defined in group_vars/host_vars.

It should also be a good idea to share some relevant information (ansible/ceph-ansible/ceph versions, OS, etc...) like mentioned in the bug report template

https://github.com/ceph/ceph-ansible/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mgariepy** [comment] 2020-09-14 14:44
What happened:

* some osd server gets created with 1 osd spawned accross all ssd instead of 1 per ssd.
* I ran the deploy twice on the cluster, the first time it was only 1 server that had this issue but the second time it was 2.

What you expected to happen:

* I would expect the osd to be populated as 1 per device when there are only the same kind of ssd in the servers
* I would also expect all the server with the same hardware to be installed the same way.

How to reproduce it (minimal and precise):
* run the deploy on clean servers.

my cluster consist of : 
* 6 ceph-ssd with 24x sata ssd
* 15 ceph-hdd  with 12x sas hdds and 2x nvme

Share your group_vars files, inventory and full ceph-ansibe log

* inventory:
```
all:
  children:
    mons:
      hosts:
        ceph-ssd1313:
        ceph-ssd[3:4]313:
    mgrs:
      hosts:
        ceph-ssd1313:
        ceph-ssd[3:4]313:
    osds:
      hosts:
        ceph-hdd130[1:9:2]:
        ceph-hdd[3:4]30[1:9:2]:
        ceph-ssd131[1:3:2]:
        ceph-ssd[3:4]31[1:3:2]:
```
* group_vars
```
# grep -v "^#\|^$" group_vars/mgrs.yml 
---
dummy:
ceph_mgr_modules: [status,prometheus]

:/etc/ansible# grep -v "^#\|^$" group_vars/osds.yml 
---
dummy:
osd_auto_discovery: true
dmcrypt: True

:/etc/ansible# grep -v "^#\|^$" group_vars/mons.yml 
---
dummy:

:/etc/ansible# grep -v "^#\|^$" group_vars/all.yml 
---
dummy:
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
fsid: <some_uuid_here>
generate_fsid: false
monitor_address_block: 10.X.Y.0/20
ip_version: ipv4
public_network: 10.X.Y.0/20
cluster_network: 10.X.Z.0/20
containerized_deployment: False
dashboard_enabled: False
```
Environment:

OS (e.g. from /etc/os-release): 20.04.1 LTS (Focal Fossa)
Kernel (e.g. uname -a): 5.4.0-47-generic
Docker version if applicable (e.g. docker version): None, I am running without container
Ansible version (e.g. ansible-playbook --version): 2.9.13
ceph-ansible version (e.g. git head or tag or stable branch): 
* commit a41c572785007079e1eeebc13a62ddbe12760aa6 (HEAD -> stable-5.0, origin/stable-5.0)

Ceph version (e.g. ceph -v): ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)

**Comment by mgariepy** [comment] 2020-09-14 14:56
which part of the ansible-log do you need ?

**Comment by dsavineau** [comment] 2020-09-14 17:47
> which part of the ansible-log do you need ?

The whole file.

Considering this might be related to ceph-volume, it could be usefull to get the ceph-volume log from the osd nodes.

**Comment by mgariepy** [comment] 2020-09-14 19:41
[ceph-volume.log.1.gz](https://github.com/ceph/ceph-ansible/files/5220580/ceph-volume.log.1.gz)

i'll provide you with the ansible logs asap. but i need to strip some info before doing so.

from what i see in the ansible run both server that are ok and those not ok run the exact same command but in the case of this server it's not quite working.

**Comment by mgariepy** [comment] 2020-09-14 20:39
After reviewing a bit of the logs, if you want or need some part of it i can pick them for you but there is so much info in that log i'd rather not post this kind of data publicly.

**Comment by mgariepy** [comment] 2020-09-15 15:14
The issue seems to be on the ceph-volume part.

i ran a creation and deletion a few time this morning and it does create the correct osd schema a few time in a row but after a while it does the wrong one with 1 block osd and the remaining 23 as block.db

**Comment by mgariepy** [comment] 2020-09-15 17:56
```
# ceph-volume --cluster ceph lvm batch --bluestore --yes --dmcrypt /dev/sdf /dev/sdo /dev/sdw /dev/sdd /dev/sdm /dev/sdu /dev/sdb /dev/sdk /dev/sds /dev/sdi /dev/sdq /dev/sdg /dev/sdx /dev/sde /dev/sdn /dev/sdv /dev/sdc /dev/sdl /dev/sdt /dev/sda /dev/sdj /dev/sdr /dev/sdh /dev/sdp --report

Total OSDs: 24

  Type            Path                                                    LV Size         % of device
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdf                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdo                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdw                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdd                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdm                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdu                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdb                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdk                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sds                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdi                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdq                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdg                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdx                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sde                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdn                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdv                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdc                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdl                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdt                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sda                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdj                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdr                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdh                                                3.49 TB         100.0%
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdp                                                3.49 TB         100.0%
```
```
# ceph-volume --cluster ceph lvm batch --bluestore --yes --dmcrypt /dev/sdf /dev/sdo /dev/sdw /dev/sdd /dev/sdm /dev/sdu /dev/sdb /dev/sdk /dev/sds /dev/sdi /dev/sdq /dev/sdg /dev/sdx /dev/sde /dev/sdn /dev/sdv /dev/sdc /dev/sdl /dev/sdt /dev/sda /dev/sdj /dev/sdr /dev/sdh /dev/sdp --report

Total OSDs: 1

Solid State VG:
  Targets:   block.db                  Total size: 80.30 TB                 
  Total LVs: 1                         Size per LV: 80.30 TB                 
  Devices:   /dev/sdo, /dev/sdw, /dev/sdd, /dev/sdm, /dev/sdu, /dev/sdb, /dev/sdk, /dev/sds, /dev/sdi, /dev/sdq, /dev/sdg, /dev/sdx, /dev/sde, /dev/sdn, /dev/sdv, /dev/sdc, /dev/sdl, /dev/sdt, /dev/sda, /dev/sdj, /dev/sdr, /dev/sdh, /dev/sdp

  Type            Path                                                    LV Size         % of device
----------------------------------------------------------------------------------------------------
  [data]          /dev/sdf                                                3.49 TB         100.0%
  [block.db]      vg: vg/lv                                               80.30 TB        100%
```

**Comment by mgariepy** [comment] 2020-09-16 16:51
here is the link to the ceph-volume bugs i filled : https://tracker.ceph.com/issues/47502

**Comment by dsavineau** [comment] 2020-09-16 21:00
Thanks for spending some time with @guits on that one.

Considering this is a ceph-volume issue and you have created a tracker for that then we can close this one.

**Closed by dsavineau** 2020-09-16 21:00 UTC
