### ISSUE TITLE
config_template doesn't recognize {% include %} correctly

### ISSUE THREAD

**Issue by chengweiv5** [ceph/ceph-ansible#899] opened 2016-07-25 11:45 UTC
Hi all,

I'm using ansible 1.9.1

```
$ ansible --version  
ansible 1.9.1
  configured module search path = None
```

and found that the generated ceph.conf by config_template doesn't correct, I mean the below part

```
#mon addr = {{ hostvars[host]['ansible_' + (hostvars[host]['monitor_interface'] if hostvars[host]['monitor_interface'] is defined else monitor_interface) ]['ipv4']['address'] }}
{% include 'mon_addr_interface.j2' %}
```

which generate a wrong `mon addr` like below

```
#mon addr = 10.15.243.179
mon addr = 10.15.234.11
```

`10.15.243.179` is the correct mon address(the only one monitor for testing) and `10.15.234.11` in fact is the osd node where the task running on it.

So the above debug says that {% include %} here doesn't pass variable correct seems the monitor  hostvars were overwritten by the osd vars.

Is this a known issue or is this a ansible issue?

**Comment by leseb** [comment] 2016-07-25 12:11
I've never seen that error before.
Not sure how come we got the IP address of an OSD since we are still running this include as part of https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L24

I don't have much time at the moment.
Would you mind investigating a bit more?

**Comment by leseb** [comment] 2016-08-10 09:58
Closing this, feel free to re-open if the issue is not solved.

**Closed by leseb** 2016-08-10 09:58 UTC
