### ISSUE TITLE
deployment stuck on "is ceph running already?" with multiple mon nodes

### ISSUE THREAD

**Issue by jprovaznik** [ceph/ceph-ansible#2201] opened 2017-11-20 09:45 UTC
On master branch (last commit 3c6f2854feb9c46ab1e1ccd3ed0fde650b01bcfa).
When 3 monitors are used (when single monitor is used then ceph-ansible passes for me) then ceph-ansible deployment is hanging on:
2017-11-20 08:53:20,144 p=18843 u=mistral |  TASK [ceph-defaults : set_fact monitor_name ansible_fqdn] **********************
2017-11-20 08:53:20,161 p=18843 u=mistral |  skipping: [192.168.24.7]
2017-11-20 08:53:20,182 p=18843 u=mistral |  TASK [ceph-defaults : is ceph running already?] ********************************

This task seems to be hanging on the node when executing following command:
[root@overcloud-controller-0 ~]# python /bin/ceph --connect-timeout 3 --cluster ceph fsid
2017-11-15 08:10:50.970903 7f9e439be700 0 -- 172.16.1.15:0/2980769618 >> 172.16.1.17:6789/0 pipe(0x7f9e3c0020c0 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x7f9e3c0008c0).fault
2017-11-15 08:10:56.971088 7f9e439be700 0 -- 172.16.1.15:0/2980769618 >> 172.16.1.14:6789/0 pipe(0x7f9e3c005d00 sd=3 :0 s=1 pgs=0 cs=0 l=1 c=0x7f9e3c007220).fault

Probably because monitors don't run on other nodes yet (my first thought is that the check runs before ceph cluster is set up).

**Comment by leseb** [comment] 2017-12-15 13:35
Closing this as we don't see this in our CI and this looks like a leftover to me.
Feel free to re-open if you experience this again.

**Closed by leseb** 2017-12-15 13:35 UTC

**Comment by tombarron** [comment] 2017-12-23 10:31
Hit this issue on master branch (last commit 0b55abe) when deploying ceph via tripleo with three controller nodes (hence 3 mons):

2017-12-23 10:03:41,729 p=26332 u=mistral |  TASK [ceph-defaults : set_fact monitor_name ansible_fqdn] **********************
2017-12-23 10:03:41,747 p=26332 u=mistral |  skipping: [192.168.24.20]
2017-12-23 10:03:41,779 p=26332 u=mistral |  TASK [ceph-defaults : is ceph running already?] ********************************

Probably we should re-open this issue?  I can help try to figure what's different between our context and CI.

Full /var/log/mistral/ceph-install-workflow.log here:
https://paste.fedoraproject.org/paste/iywsZw3cxoR8JxJbc5fhZg

**Comment by leseb** [comment] 2018-01-02 10:11
Can you send the log again? (expired)

**Comment by tombarron** [comment] 2018-01-03 21:36
Yeah, I'll see if it reproduces with current master everywhere.  Maybe we'll get lucky and it won't.

**Comment by tombarron** [comment] 2018-01-04 11:28
So far I haven't been able to reproduce the issue, i.e. deploying with three controllers succeeds.  ceph-ansible head is now at 9c5e8ce79ae5bd99aa7df6476a693fa1ca8c5ba0. I was trying to reproduce with a minimal overcloud deployment - no mds, cephfs, manila, ganesha or isolated networks.  Now I'll add these ingredients back in and (/me crosses fingers) hopefully there will still be no issue.

**Comment by uhlhosting** [comment] 2020-02-22 18:52
Got the same issue

**Comment by mafonso** [comment] 2020-05-12 00:44
Seeing the same issue. 
I believe it has to do with python3/pip3. 
It works fine it I allow python2/pip to be installed.
