### ISSUE TITLE
Ceph-ansible OSD node add fail (ceph.volume Failed to find physical volume)

### ISSUE THREAD

**Issue by mosharaflink** [ceph/ceph-ansible#6043] opened 2020-11-17 10:28 UTC
Using ceph nautilus (v 14.2.13) last couple of months and installed using ceph-ansible version 4. Recently facing a problem of OSD node failure. While readd the osd node by reinstalling the OS generates an error as below: 

**Deployment Node:
```
An exception occurred during task execution. To see the full traceback, use vvv. The error was: TypeError: list indices must be integers, not str
fatal: [ceph1.bol-online.com]: FAILED! => changed=false
module_stderr: |
Traceback (most recent call last):
File "<stdin>", line 114, in <module>
File "<stdin>", line 106, in ansiballz_main
File "<stdin>", line 49, in invoke_module
File "/tmp/ansible_ceph_volume_payload_FSVLCL/_main__.py", line 685, in <module>
File "/tmp/ansible_ceph_volume_payload_FSVLCL/__main__.py", line 681, in main
File "/tmp/ansible_ceph_volume_payload_FSVLCL/__main__.py", line 648, in run_module
TypeError: list indices must be integers, not str
module_stdout: ''
msg: |-
MODULE FAILURE
See stdout/stderr for the exact error
```

**OSD Node Error:
```
[2020-11-16 17:36:04,838][ceph_volume.process][INFO ] Running command: /bin/lsblk --nodeps P -o NAME,KNAME,MAJ:MIN,FSTYPE,MOUNTPOINT,LABEL,UUID,RO,RM,MODEL,SIZE,STATE,OWNER,GROUP,MODE,ALIGNMENT,PHY-SEC,LOG-SE
C,ROTA,SCHED,TYPE,DISC-ALN,DISC-GRAN,DISC-MAX,DISC-ZERO,PKNAME,PARTLABEL /dev/sdk
[2020-11-16 17:36:04,845][ceph_volume.process][INFO ] stdout NAME="sdk" KNAME="sdk" MAJ:MIN="8:160" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="INTEL SSDSC2KB01" SIZE="1.8T" STATE="running" O
WNER="root" GROUP="disk" MODE="brw-rw---" ALIGNMENT="0" PHY-SEC="4096" LOG-SEC="512" ROTA="0" SCHED="mq-deadline" TYPE="disk" DISC-ALN="0" DISC-GRAN="0B" DISC-MAX="0B" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2020-11-16 17:36:04,846][ceph_volume.process][INFO ] Running command: /sbin/blkid -p /dev/sdk
[2020-11-16 17:36:04,857][ceph_volume.process][INFO ] Running command: /sbin/pvs --noheadings --readonly --units=b --nosuffix --separator=";" -o vg_name,pv_count,lv_count,vg_attr,vg_extent_count,vg_free_count,
vg_extent_size /dev/sdk
[2020-11-16 17:36:04,885][ceph_volume.process][INFO ] stderr Failed to find physical volume "/dev/sdk".
[2020-11-16 17:36:04,886][ceph_volume.process][INFO ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sdk
[2020-11-16 17:36:04,911][ceph_volume.process][INFO ] stderr unable to read label for /dev/sdk: (2) No such file or directory
[2020-11-16 17:36:04,912][ceph_volume.process][INFO ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sdk
[2020-11-16 17:36:04,937][ceph_volume.process][INFO ] stderr unable to read label for /dev/sdk: (2) No such file or directory
[2020-11-16 17:36:04,937][ceph_volume.process][INFO ] Running command: /sbin/udevadm info --query=property /dev/sdk
[2020-11-16 17:36:04,943][ceph_volume.process][INFO ] stdout DEVLINKS=/dev/disk/by-id/wwn-0x55cd2e415222cdf8 /dev/disk/by-id/scsi-355cd2e415222cdf8 /dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:11:0
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout DEVNAME=/dev/sdk
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout DEVPATH=/devices/pci0000:00/0000:00:02.2/0000:02:00.0/host0/target0:0:11/0:0:11:0/block/sdk
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout DEVTYPE=disk
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout ID_BUS=scsi
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout ID_MODEL=INTEL_SSDSC2KB01
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout ID_MODEL_ENC=INTEL\x20SSDSC2KB01
[2020-11-16 17:36:04,944][ceph_volume.process][INFO ] stdout ID_PATH=pci-0000:02:00.0-scsi-0:0:11:0
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_PATH_TAG=pci-0000_02_00_0-scsi-0_0_11_0
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_REVISION=0120
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_SCSI=1
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_SCSI_SERIAL=PHYF006002QA1P9DGN
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_SERIAL=355cd2e415222cdf8
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_SERIAL_SHORT=55cd2e415222cdf8
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_TYPE=disk
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_VENDOR=ATA
[2020-11-16 17:36:04,945][ceph_volume.process][INFO ] stdout ID_VENDOR_ENC=ATA\x20\x20\x20\x20\x20
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout ID_WWN=0x55cd2e415222cdf8
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout ID_WWN_WITH_EXTENSION=0x55cd2e415222cdf8
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout MAJOR=8
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout MINOR=160
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout SUBSYSTEM=block
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout TAGS=:systemd:
[2020-11-16 17:36:04,946][ceph_volume.process][INFO ] stdout USEC_INITIALIZED=15991838
[2020-11-16 17:36:04,947][ceph_volume.process][INFO ] Running command: /sbin/lvs --noheadings --readonly --separator=";" -a --units=b --nosuffix -S lv_path=/dev/sdh -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,l
v_size
[2020-11-16 17:36:04,973][ceph_volume.process][INFO ] Running command: /bin/lsblk --nodeps -P -o NAME,KNAME,MAJ:MIN,FSTYPE,MOUNTPOINT,LABEL,UUID,RO,RM,MODEL,SIZE,STATE,OWNER,GROUP,MODE,ALIGNMENT,PHY-SEC,LOG-SE
```

**Comment by guits** [comment] 2020-11-17 12:34
please, as asked in the ML, share group_vars, inventory and full ceph-ansible log

**Comment by mosharaflink** [comment] 2020-11-18 07:03
[](url)
[cpeh_ansible .zip](https://github.com/ceph/ceph-ansible/files/5558296/cpeh_ansible.zip)
Hi guits
all.yml, osds.yml and ceph-ansible log has been attached for you consideration.

**Comment by sli720** [comment] 2020-11-19 10:29
I have exactly the same error while deploying a ceph cluster under centos 7.9. I seems as ceph-volume can not find the devices:
`ceph-volume --cluster ceph lvm batch --bluestore --yes /dev/sdb
--> DEPRECATION NOTICE
--> You are using the legacy automatic disk sorting behavior
--> The Pacific release will change the default to --no-auto
--> passed data devices: 0 physical, 0 LVM
--> relative data size: 1.0
--> All data devices are unavailable`

**Comment by sli720** [comment] 2020-11-19 10:50
Running the ceph-volume command with --no-auto created the osd disk successfully on my system.

**Comment by mosharaflink** [comment] 2020-11-19 11:51
Manually running with --no-auto seems ok. But to run it automate with ceph-ansible script, which file needs to be updated with --no-auto??

**Comment by mosharaflink** [comment] 2020-11-19 12:27
I got the settings wherer to put the no-auto. But after that while running the ceph-ansible script can't find lsblk id 

[2020-11-19 18:18:30,848][ceph_volume.process][INFO  ] Running command: /sbin/blkid -p /dev/sda
[2020-11-19 18:18:30,902][ceph_volume.process][INFO  ] Running command: /sbin/pvs --noheadings --readonly --units=b --nosuffix --separator=";" -o vg_name,pv_count,lv_count,vg_attr,vg_extent_count,vg_free_count,vg_extent_size /dev/sda
[2020-11-19 18:18:30,947][ceph_volume.process][INFO  ] stderr Failed to find physical volume "/dev/sda".
[2020-11-19 18:18:30,948][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sda
[2020-11-19 18:18:30,977][ceph_volume.process][INFO  ] stderr unable to read label for /dev/sda: (2) No such file or directory

**Comment by sli720** [comment] 2020-11-19 12:52
@mosharaflink In which yml did you add --no-auto?

**Comment by mosharaflink** [comment] 2020-11-19 12:54
@sli720 its not in yml file. Its on ceph_volume.py and I see that command is passing.

**Comment by sli720** [comment] 2020-11-19 13:23
@mosharaflink Are you also using centos 7.9? Cause I used the same playbooks with centos 7.8 successfully before and they stopped working after upgrading to centos 7.9.  

@guits Don't know if this is related or just a coincidence. Is the ceph-ansible project already compatible with centos 7.9?

**Comment by dsavineau** [comment] 2020-11-19 15:20
There's nothing related to CentOS release here.

Starting Ceph Nautilus 14.2.13, ceph-volume introduced a regresion in the lvm batch command when using only SSD devices [1].
A fix on ceph-volume is pending to be merged [2] and will probably be present in 14.2.15 at some point.

As mentioned @mosharaflink the only manual workaround for this, is to add the `--no-auto` parameter into the ceph_volume ansible module.
Othewise you could stick to a previous Ceph Nautilus release (like 14.2.12)

Note that, this should be only needed when using lvm batch (ie: via `devices` parameter) AND using only SSD devices.
If you're using only HDD or HDD/SSD mixed then everything is fine.

We won't patch the ceph_volume ansible module in ceph-ansible because the issue is coming from the ceph-volume tool itself.

[1] https://tracker.ceph.com/issues/48106
[2] https://github.com/ceph/ceph/pull/38046

**Closed by dsavineau** 2020-11-19 15:20 UTC
Labels: needs info

**Comment by sli720** [comment] 2020-11-19 16:33
Thanks for clarifying. Where can I configure the specific version I want to install. Setting

ceph_release_num:
  nautilus: 14.2.12

did not work

**Comment by dsavineau** [comment] 2020-11-19 16:50
That's unfortunatly not possible via ceph-ansible and nautilus (but it works for octopus because each releases are stored in a different repository) so you will need to do some manual steps prior the ceph-ansible execution.

You can use yum versionlock to pin to 14.2.12 for instance. But this requires to already setup the ceph repository.

```console
$ yum install -y yum-plugin-versionlock
$ yum install -y epel-release https://download.ceph.com/rpm-nautilus/el7/noarch/ceph-release-1-1.el7.noarch.rpm
$ yum versionlock add '*ceph*-14.2.12-0.el*'
Loaded plugins: fastestmirror, ovl, versionlock
Loading mirror speeds from cached hostfile
 * base: centos.mirror.colo-serv.net
 * epel: mirror.dst.ca
 * extras: centos.mirror.colo-serv.net
 * updates: centos.mirror.colo-serv.net
Adding versionlock on: 2:ceph-14.2.12-0.el7
Adding versionlock on: 2:ceph-base-14.2.12-0.el7
Adding versionlock on: 2:ceph-common-14.2.12-0.el7
Adding versionlock on: 2:ceph-debuginfo-14.2.12-0.el7
Adding versionlock on: 2:ceph-fuse-14.2.12-0.el7
Adding versionlock on: 2:ceph-mds-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-14.2.12-0.el7
Adding versionlock on: 2:ceph-mon-14.2.12-0.el7
Adding versionlock on: 2:ceph-osd-14.2.12-0.el7
Adding versionlock on: 2:ceph-radosgw-14.2.12-0.el7
Adding versionlock on: 2:ceph-resource-agents-14.2.12-0.el7
Adding versionlock on: 2:ceph-selinux-14.2.12-0.el7
Adding versionlock on: 2:ceph-test-14.2.12-0.el7
Adding versionlock on: 2:cephfs-java-14.2.12-0.el7
Adding versionlock on: 2:libcephfs-devel-14.2.12-0.el7
Adding versionlock on: 2:libcephfs2-14.2.12-0.el7
Adding versionlock on: 2:libcephfs_jni-devel-14.2.12-0.el7
Adding versionlock on: 2:libcephfs_jni1-14.2.12-0.el7
Adding versionlock on: 2:python-ceph-argparse-14.2.12-0.el7
Adding versionlock on: 2:python-ceph-compat-14.2.12-0.el7
Adding versionlock on: 2:python-cephfs-14.2.12-0.el7
Adding versionlock on: 2:python3-ceph-argparse-14.2.12-0.el7
Adding versionlock on: 2:python3-cephfs-14.2.12-0.el7
Adding versionlock on: 2:ceph-grafana-dashboards-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-dashboard-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-diskprediction-cloud-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-diskprediction-local-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-k8sevents-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-rook-14.2.12-0.el7
Adding versionlock on: 2:ceph-mgr-ssh-14.2.12-0.el7
versionlock added: 30
```

And maybe do the same for rbd and rados packages.

**Comment by mosharaflink** [comment] 2020-11-22 11:00
@dsavineau Currently I am using ubuntu 18.04 for my Ceph cluster version (ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)). 
Do you suggest me to use Ceph Nautilus release (like 14.2.12) as --no-auto not worked for version 14.2.8?

**Comment by sli720** [comment] 2020-11-22 11:36
> @dsavineau Currently I am using ubuntu 18.04 for my Ceph cluster version (ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)). 
> Do you suggest me to use Ceph Nautilus release (like 14.2.12) as --no-auto not worked for version 14.2.8?

Yes with <= 14.2.12 it worked for me

**Comment by mosharaflink** [comment] 2020-11-23 01:59
@sli720 As I said earlier, we are using OS Ubuntu18 and ceph-ansible v4. Version 14.2.8 is automatically generated by the ceph-ansible script. is there any procedure to install 14.2.12 using ceph-ansible??

**Comment by dsavineau** [comment] 2020-11-24 17:03
> As I said earlier, we are using OS Ubuntu18 and ceph-ansible v4. Ceph version 14.2.8 is automatically generated by the ceph-ansible script

ceph-ansible should always install the latest ceph release (14.2.15 at the moment) when using `ceph_origin: repository` and `ceph_repository: community` so I'm not sure why you have 14.2.8 on Ubuntu 18.04

**Comment by SachinMaharana** [comment] 2020-12-08 06:59
Is the issue still in 14.2.15? I am getting the same error, and i tried passing --no-auto but was not sure where to pass it in ceph-volume.py in ansible. Any suggestions?

**Comment by mosharaflink** [comment] 2020-12-08 08:14
@SachinMaharana I'm using CEPH v14.2.13 with ansible version 4. But passing no-auto not helped me to resolve the isseue. Still searching for a solution for this.
However, did you mixup SSD+HDD in the cluster???

**Comment by dsavineau** [comment] 2020-12-08 15:11
> Is the issue still in 14.2.15? I am getting the same error, and i tried passing --no-auto but was not sure where to pass it in ceph-volume.py in ansible. Any suggestions?

14.2.15 should have the ceph-volume fix

**Comment by mosharaflink** [comment] 2020-12-20 09:39
@dsavineau: the issue not yet resolved?? 

We are suffering a lot due to this limitation; Need an immediate solution to resolve the problem otherwise there will be a disaster for me in my live environment.

**Comment by SachinMaharana** [comment] 2020-12-20 09:42
@dsavineau Well i saw the same issue with confirming after confirming i have 14.2.15. 

@mosharaflink Have you tried this? https://github.com/ceph/ceph-ansible/issues/6043#issuecomment-730501729 
This fixed it for me.

**Comment by foysalkayum** [comment] 2020-12-20 10:07
> @dsavineau Well i saw the same issue after confirming i have 14.2.15.
> 
> @mosharaflink Have you tried this? [#6043 (comment)](https://github.com/ceph/ceph-ansible/issues/6043#issuecomment-730501729)
@SachinMaharana  we are unable to try this as we are using Ubuntu 18.04. Any other way for the work around?
> This fixed it for me.

**Comment by discostur** [comment] 2021-01-18 11:49
@dsavineau just tested to bootstrap a new ceph cluster - the error is still present in ceph `v14.2.16`. I did a **HDD only** deployment!

Wether i select 
```
osd_auto_discovery: true
``` 

or explicit name the OSD devices
```
devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
``` 

i get the following error:
```
TASK [ceph-osd : use ceph-volume lvm batch to create bluestore osds] ***********************************************************************************************************************************************************************************************************
Monday 18 January 2021  12:15:05 +0100 (0:00:00.139)       0:02:20.445 ******** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: list indices must be integers, not str
fatal: [ceph-k8s-test.intern.customer-virt.eu]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_ceph_volume_payload_O4MDKU/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 744, in <module>
      File "/tmp/ansible_ceph_volume_payload_O4MDKU/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 740, in main
      File "/tmp/ansible_ceph_volume_payload_O4MDKU/ansible_ceph_volume_payload.zip/ansible/modules/ceph_volume.py", line 707, in run_module
    TypeError: list indices must be integers, not str
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  ```

**Comment by discostur** [comment] 2021-02-10 15:06
@dsavineau please reopen - issue is still present
