### ISSUE TITLE
msg: chown failed: failed to look up user ceph

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#641] opened 2016-03-22 12:44 UTC
WIth RHCS 1.3.1 = Ceph Hammer .iso install, I get this error very early:

TASK: [ceph.ceph-common | create ceph conf directory] ************************* 
failed: [cephmon2] => {"failed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/ceph", "size": 6, "state": "directory", "uid": 0}
msg: chown failed: failed to look up user ceph

It appears that ceph-ansible now concludes that we are using Infernalis or later (BTW it would be nice if the "is_ceph_infernalis" variable was named "after_ceph_hammer" instead).  One problem is that "rh_storage_version" is not defined because we attempted to get the RPM version of ceph-common before we installed the RPM.   Why didn't it stop there?  The culprit is "failed_when: false".  This should not be used everywhere.

- name: get ceph rhcs version
  shell: rpm -q --qf "%{version}\n" ceph-common | cut -f1,2 -d '.'
  changed_when: false
  failed_when: false
  register: rh_storage_version
  when: ceph_stable_rh_storage

So why did the preceding step not determine the correct version?  It appears that when clause for step to install Ceph mon RPMs broke.  Looking at the when clause for the monitor RPM install in roles/ceph-common/tasks/installs/install_on_redhat.yml :

    (ceph_origin == "distro" or ceph_stable_rh_storage) and
    mon_group_name in group_names and
    ansible_pkg_mgr == "yum" and
    ceph_stable and
    ceph_stable_release not in ceph_stable_releases

I thought we either set ceph_stable_rh_storage OR we set ceph_stable, not both.  So I patched the when clause to look like this:

    (ceph_origin == "distro" or ceph_stable_rh_storage or ceph_stable) and
    mon_group_name in group_names and
    ansible_pkg_mgr == "yum" 

The ceph_stable_releases variable - what does this mean exactly?  Why do we need it?  When should it be updated?

This logic is getting complicated enough that I'm having trouble following it.

I dont want to generate a pull request because I am not familiar with all possible environments for this install.  CI (continuous integration) testing would make me more confident about submitting pull requests.

**Comment by leseb** [comment] 2016-03-22 17:07
Hi @bengland2, yes sorry about that.
I have to admit that trying to support all the Ceph releases has kinda brought more difficulties to read the code than solving problems...

There are 2 sides:

* first side: ceph community versions. They are activated by the flag `ceph_stable` and then the distro is chose with the `ceph_stable_release`.
* second side: ceph enterprise versions: ICE and `ceph_stable_rh_storage` (should probably rename this 'rhcs' at some point...). ICE stands for the old Inktank Ceph enterprise and is deprecated. `ceph_stable_rh_storage`

The issues, with the community version it is easier to track which version is installed thanks to the flaf `ceph_stable_release`, then later we can already check which Ceph version is going to be installed before having to run `apt`. So this is where the variable `ceph_stable_releases` (see the 's') comes in. This variable contains the names all the releases before Infernalis. Later we can check for everything different than this variable to detect that we run infernalis. So this variable will probably never be modified.

With rhcs it is a bit more complex, we actually don't explicitly ask which version is going to be installed, users just take the last one from the CDN or just the one on the ISO. This is why we have to check the ceph version (in order to detect is if run infernalis or not) using rpm **when** the package is installed.

Are you running from master because as far as I see the get_version is after the package installation: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/main.yml#L67

Your `when` patch is correct, please submit a PR :) + we can remove the failed_when from the get_version too.

ps: agreed we should probably rename the fact by `after_ceph_hammer`. I should have used that from the beginning. If you want to PR this i'm also fine with it.

**Comment by alfredodeza** [comment] 2016-04-01 11:43
BZ created related to this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1322991

@leseb I think that renaming `ceph_stable` to `ceph_community_release` is a bit better and more true to what it is. Using `ceph_stable` implies that anything else is not stable :)

Doing that makes it easier to follow the convention for the other variables:

`ceph_rh_release`
`ceph_community_releases`

Right now, although not functional (renaming variables don't fix anything here) it would be a nice to have. Maybe a separate ticket to track that functionality would be desirable.

For the linked BZ ticket, the simple fix is not to try to change the ownership when it isn't Infernalis (the release is some version of Giant). That wouldn't be good long term though, I mostly agree with what Ben mentions.

**Comment by leseb** [comment] 2016-04-01 16:19
I just deployed a cluster on RHEL 7.2 with RHCS ISO 1.3.2 and I can not reproduce this problem.
I think this was fixed a couple of commits ago. I'm closing this, feel free to re-open if necessary.

@bengland2, @alfredodeza I'll be happy to do some renaming regarding variable names.
@alfredodeza perhaps you can take this item?

Thanks in advance!

**Closed by leseb** 2016-04-01 16:19 UTC
