### ISSUE TITLE
Add support for 16.2.5 for arm64 to Launchpad for Focal and Hirsute 

### ISSUE THREAD

**Issue by devinjdawson** [ceph/ceph-ansible#6868] opened 2021-08-29 21:22 UTC
16.2.4 has been cited as not working with certain arm64 processors. 
if 16.2.5 does in fact work, please add this .deb package to launchpad, otherwise installations will fail to provision and Ceph packages will continue to not work.

**Comment by dsavineau** [comment] 2021-09-01 17:42
I'm not sure to understand the request.
We don't manage anything on launchpad for specific Ubuntu releases.
ceph-ansible uses `https://download.ceph.com/debian-pacific/`  for Pacific on Debian/Ubuntu distros when using `ceph_origin: repository` and `ceph_repository: community`.
This repository already contains the v16.2.5 release.

**Comment by dsavineau** [comment] 2021-09-01 19:29
> 2-3 months ago, the only Arm64 packages that were available with a modern release of ceph were released only on Hirsute, not Focal, meaning if you wanted to use ceph-ansible on Arm64 with Ubuntu, it had to be updated to a non-LTS version of the OS.

That's not true. Ceph Pacific has always been released on multiple Ubuntu LTS versions for both x86_64 and arm64 architectures [1][2][3]
 - xenial
 - bionic

> As of now, since that was version 16.2.4, there are no working versions for for Arm64 on launchpad, given that 16.2.5 has the bug fix and is not and has bot been made readily available.

Again, We (ceph-ansible maintainers nor ceph core/infra maintainers) manage/support/publish ceph releases on launchpad.
That's why I'm mentioning using `download.ceph.com` which is the place where the ceph packages are published for every ceph releases and present in the ceph documentation [4]

> So, not only did I update my entire operating system for a cluster of a machines for a bug with the software, even after the update it’s still not made readily available from developers.

And I don't even know what's your issue is with arm64 and 16.2.4 but if you're saying your issue is fixed in 16.2.5 then you already have the fix available.

> I’m sure the documentation says to do what you just told me, but if you actually tried it, you would come across a variety of issues that do not allow the installation to complete, hence the previous post.

Again, look at the ceph documentation about the packages [4] then if you have an issue deploying with arm64 coming from ceph itself then I don't know why you open an issue here.

> Therefore, it would be nice if the documentation and the maintaining of this package/app was looked into and given a little more attention.

And that's maybe the problem here, again, if you're using a repository from launchpad which isn't part of the ceph documentation then that's at your own risk.
You can also try to contact the launchpad maintainers [5]

[1] https://download.ceph.com/debian-pacific/dists/
[2] https://download.ceph.com/debian-pacific/pool/main/c/ceph/
[3] https://docs.ceph.com/en/latest/releases/pacific/#general
[4] https://docs.ceph.com/en/latest/install/get-packages/#debian-packages
[5] https://launchpad.net/ceph

**Comment by devinjdawson** [comment] 2021-09-01 20:33
16.2.4 is not compatible with upgraded 20.4 releases due to dependencies

**Comment by dsavineau** [comment] 2021-09-01 21:13
> 16.2.4 is not compatible with upgraded 20.4 releases due to dependencies...

Which package ? Which dependency ?

Saying it doesn't work is one thing, giving details is better.

> also it wouldn't matter the executable doesn't run anyway.

Again, if your issue is fixed in 16.2.5 then I don't see why we should keep this issue open, especially if ceph-ansible has nothing to do in the problem.

**Closed by dsavineau** 2021-09-01 21:13 UTC
Labels: needs info

**Comment by devinjdawson** [comment] 2021-09-02 00:46
Please, follow along here:

Because 16.2.4 was not compatible with Focal, it forced people to upgrade to Hirsute. However, you do not support hirsute, nor is 16.2.5 available through launchpad. I can NOT confirm that 16.2.5 works with Focal 20.04.3. I would assume it does not given the decencies are most likely the same. This would once again force a user to upgrade to Hirsute from Focal 20.04.3 if they are running Arm64.

This issue needs to be addressed because I got into this mess following your documentation. It would be nice if you looked into the application releases and package management, particularly for Arm64. There is insufficient attention being dedicated to Ubuntu compatibility and releases. I understand that Launchpad is not being maintained by you, but you guys are the developers and apparently they have some misconception on what should be released. 

Please, takes some initiative here. Thank you.

**Comment by dsavineau** [comment] 2021-09-02 13:46
> Because 16.2.4 was not compatible with Focal, it forced people to upgrade to Hirsute.

Nobody is forcing you to upgrade, that's your choice.

> However, you do not support hirsute, nor is 16.2.5 available through launchpad.

As I said, we're not related to launchpad at all and Pacific is only supported for Ubuntu Bionic and Focal.

> I can NOT confirm that 16.2.5 works with Focal 20.04.3. I would assume it does not given the dependencies are most likely the same.

And again, I don't know what dependencies you're talking about. I just tried an AIO deployment on Focal arm64 with the packages from download.ceph.com and it worked well.

> This would once again force a user to upgrade to Hirsute from Focal 20.04.3 if they are running Arm64.

> This issue needs to be addressed because I got into this mess following your documentation. 

I don't even know your is exactly your issue but I can give you two solutions:
 - talk to the launchpad maintainers if you need 16.2.5 for Hirsute
 - open an issue on https://tracker.ceph.com/
If ceph-ansible is failing due to external issue then that's not our responsibility to fix them.

> It would be nice if you looked into the application releases and package management, particularly for Arm64. There is insufficient attention being dedicated to Ubuntu compatibility and releases. I understand that Launchpad is not being maintained by you, but you guys are the developers and apparently they have some misconception on what should be released.

Again, I invite you to open an issue on the ceph tracker directly for stuff related to ceph core itself.

**Comment by devinjdawson** [comment] 2021-09-04 21:27
Honestly I feel like you are not reading your own responses here. If its not compatible with 16.2.4, that means you have to upgrade to run Ceph. Sure, I dont have to run Ceph, but that than defeats the whole point of this, doesn't it? 

There is somewhat of a plausible solution that is offered from Ubuntu, and it requires rerunning the failed site.yml file with the 'distro' setting so reset the apt repositories. But, if you upgrade Ubuntu to Impish (21.10) it should be compatible, once again when ran with the 'distro' setting after upgrade. I dont know this for a fact, but I'm guessing that this will resolve dependencies and I am in the middle of trying it now. 

I understand your frustration that I can not tell you specifically which dependencies are not allowing 16.2.4>= to run on 20.04.3, but that would require me to downgrade my machines to do QA for you guys, which, one,  would have been different if you guys asked, and two, more of a waste of my time from following your documentation (or lack thereof), which seems to be where all of these issues stem from. 

anyway, I'm sure someone will come across this (or not)... but at least a solution is here now.

**Comment by dsavineau** [comment] 2021-09-08 19:01
> Honestly I feel like you are not reading your own responses here. If its not compatible with 16.2.4, that means you have to upgrade to run Ceph.

No you don't have to because you have alternate solutions but since you won't want to share the exact root cause of your issue then I can't tell you what is the best way to fix it.

Of course, if 16.2.4 isn't working for you but 16.2.5 is, then this implies you to upgrade unless:

- you switch to a containerized deployment (`containerized_deployment: true`). Since you mentioned that your issue is related to package dependencies then using a containerized setup will probably solve that problem.
- you use pacific devel content (16.2.4 + fix merged in the pacific branc) which should include your fix. This doesn't make sense now 16.2.5 is out but using the devel repository (`ceph_origin: repository` and `ceph_repository: dev`) on shaman will allow you to use content from the upstream pacific branch.

> I understand your frustration that I can not tell you specifically which dependencies are not allowing 16.2.4>= to run on 20.04.3, but that would require me to downgrade my machines to do QA for you guys, which, one, would have been different if you guys asked

I'm not asking you to downgrade your nodes to reproduced the issue but at least when you open an issue saying this isn't working then provide some useful information.
At best share a ceph tracker link or something else related to the resolution of this issue.

> and two, more of a waste of my time from following your documentation (or lack thereof), which seems to be where all of these issues stem from.

Again, your issue isn't related directly to ceph-ansible. The fact that ceph-ansible is failing is only the consequence of 16.2.4 not beeing compatible with ubuntu 20.04 on arm64 and I don't see what we could do on ceph-ansible for this issue.

If you think there's a lack of documentation, then open a github issue with detailed information or even better, create a PR.
Any contributions are welcome.
