### ISSUE TITLE
Stuck on task "ceph-mon : collect admin and bootstrap keys"

### ISSUE THREAD

**Issue by fangzhechang** [ceph/ceph-ansible#799] opened 2016-05-19 16:07 UTC
I'm installing Jewel on three Centos 7 machines behind a firewall using ceph-ansible. After adding environment variables to a few tasks, I can download and install the packages. However, it got stuck on the step:
TASK [ceph-mon : collect admin and bootstrap keys] *****************************
task path: /home/fangzhe/projects/ceph/ceph-ansible/roles/ceph-mon/tasks/start_monitor.yml:48

As a result, multiple copies of the following processes are running on each of the target machines:

> /usr/bin/ceph-mon -f --cluster ceph --id <host name> --setuser ceph --setgroup ceph
> python /sbin/ceph-create-keys --cluster ceph --id <host name>

$ceph status complains

> auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory

Any suggestions is appreciated.

Thanks.

Fangzhe

**Comment by leseb** [comment] 2016-05-20 11:47
duplicate of #790 
closing this.

**Closed by leseb** 2016-05-20 11:47 UTC
