### ISSUE TITLE
Ceph Hammer: Unit ceph-radosgw.service failed to load (again!)

### ISSUE THREAD

**Issue by ASBishop** [ceph/ceph-ansible#843] opened 2016-06-03 20:48 UTC
I am able to reproduce the problem reported in #642. Everything works fine the first time I deploy the cluster, but if I run purge-cluster.yml and deploy again it will fail. This is when deploying ceph_stable_rh_storage on RHEL 7.2, when mons and rgws are on the same hosts.

After the install fails, I notice the systemd unit file for 'ceph' is present, but the one for 'ceph-radosgw' is missing. These files are (or should be) in /var/run/systemd/generator.late.

Upon investigation, I see the 'ceph' RPM (ceph-0.94.5-9.el7cp.x86_64.rpm) has a postinstall scriptlet that executes "/sbin/chkconfig --add ceph" and that causes systemd to re-run its generators, which in turn creates the unit file.

However, the 'ceph-radosgw' RPM (ceph-radosgw-0.94.5-9.el7cp.x86_64.rpm) does not run chkconfig in its postinstall scriptlet. My guess is the first time a cluster is deployed, something else causes the systemd generators to run some time after ceph-radosgw is installed. However, this does not appear to happen after a purge and redeploy.

The fact that the ceph-radosgw RPM isn't running chckconfig on installation may well be a bug to file with Red Hat. Meanwhile, I found a workaround, and that is to add the following task at the very end of install_on_redhat.yml:

- name: trigger creation of ceph-radosgw systemd unit file
  command: chkconfig --add ceph-radosgw
  when:
    - rgw_group_name in group_names

**Comment by leseb** [comment] 2016-06-06 09:19
@ASBishop thanks for investigating.
Adding @ktdreyer to this thread for the potential package issue.

Did you check if other packages (mon, osd) also have this `chkconfig --add ceph*`?
Thanks!

**Comment by ASBishop** [comment] 2016-06-06 12:36
The mon and osd functionality are governed by the 'ceph' daemon. The packages are dependent on the ceph RPM, which we know calls chkconfig. So mon and osd are OK.

ceph-radosgw runs its own daemon, and therefore the RPM should call chkconfig.

I have no experience with mds (not using it).

**Comment by leseb** [comment] 2016-08-10 09:57
Closing this, feel free to re-open if the issue is not solved.

**Closed by leseb** 2016-08-10 09:57 UTC

**Comment by ASBishop** [comment] 2016-08-10 12:10
Was there a change that should have solved the issue?

**Comment by leseb** [comment] 2016-08-16 07:42
Not really, can you tell me if you're still having this issue?

**Comment by ASBishop** [comment] 2016-08-16 19:33
I've been using a local workaround. I could submit it as a proposed fix, but held off in the hope we would hear whether the RPM issue is the root of the problem. I didn't want to submit a patch that obscured a separate problem.

I'll submit the patch and see what you think.
