### ISSUE TITLE
Unsupported parameters for (copy) module

### ISSUE THREAD

**Issue by kevin58796B** [ceph/ceph-ansible#3112] opened 2018-09-12 02:14 UTC
install ceph with  ceph-ansible stable3.1

errors follows:

TASK [ceph-config : generate ceph configuration file: ceph.conf] **********************************************************************************************************
Wednesday 12 September 2018  10:03:44 +0800 (0:00:00.885)       0:01:11.070 *** 
fatal: [100.75.1.16]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (copy) module: original_basename Supported parameters include: _original_basename, attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"}

**Comment by guits** [comment] 2018-09-12 12:12
which ansible version are you using?

**Comment by ecmrauh** [comment] 2018-09-12 13:47
This seems like a duplicate of https://github.com/ceph/ceph-ansible/issues/2843.

I have the same problem. I am using Ansible version 2.6.3 (from Debian stretch-backports) and we would like to use stable-3.1.x.

@guits, you mentioned (https://github.com/ceph/ceph-ansible/issues/2843#issuecomment-411032555) that you don't think stable-3.1 is intended to run against Ansible 2.6. Is this still true? And what is expected to work with which Ansible version?

**Comment by ecmrauh** [comment] 2018-09-12 14:03
According to http://docs.ceph.com/ceph-ansible/master/index.html#releases, the master branch supports Ansible version 2.6. But a test with the current master branch leads to the following error message:

    TASK [ceph-config : create ceph conf directory]
    ERROR! Unexpected Exception, this is probably a bug: cannot import name to_bytes

**Comment by guits** [comment] 2018-09-12 23:03
@ecmrauh yes, it is still true.
We currently run our tests on master against ansible 2.6, we don't hit this issue though.

Could provide more details ? What's your setup ?

**Comment by ecmrauh** [comment] 2018-09-13 06:44
I actually didn't run the latest commit on master and the error is gone now. Sorry for the noise!

**Comment by leseb** [comment] 2018-09-26 08:32
Closing this for low activity.

**Closed by leseb** 2018-09-26 08:32 UTC
