### ISSUE TITLE
site.yml error : "choose an installation origin between repository, distro and local"

### ISSUE THREAD

**Issue by daejung** [ceph/ceph-ansible#2533] opened 2018-04-19 08:20 UTC
`TASK [ceph-common : make sure an installation origin was chosen] *****************************
Thursday 19 April 2018  08:03:21 +0000 (0:00:00.189)       0:00:38.296 ********`
`fatal: [mon1]: FAILED! => {"changed": false, "msg": "choose an installation origin between repository, distro and local\nValid ceph_origin are: [u'repository', u'distro', u'local']"}`
`fatal: [mon2]: FAILED! => {"changed": false, "msg": "choose an installation origin between repository, distro and local\nValid ceph_origin are: [u'repository', u'distro', u'local']"}`
`fatal: [mon3]: FAILED! => {"changed": false, "msg": "choose an installation origin between repository, distro and local\nValid ceph_origin are: [u'repository', u'distro', u'local']"}`

Ubuntu 16.04
ansible 2.5.1

i was clone 'ceph-ansible' -> write 'ceph'file and 'osds'file -> run "ansible-playbook site.yml(site.yml.sample)"

i can't find same error on 'git issues'.. and just think error on ceph_origin get repository, distro and local...? help me
consider that I'm not good at english . you may not understand my word..

**Comment by leseb** [comment] 2018-04-19 08:40
The error is pretty self-explanatory, you need to edit `group_vars/all.yml` and chose your installation source. Also please look into the doc: http://docs.ceph.com/ceph-ansible/master/

I'm closing this now since this is not a bug, simply a configuration issue.
Thanks.

**Closed by leseb** 2018-04-19 08:40 UTC
