### ISSUE TITLE
Broken vagrantfile

### ISSUE THREAD

**Issue by visbits** [ceph/ceph-ansible#898] opened 2016-07-24 23:11 UTC
Looks like the last few commits and push broke the vagrant file.

tyler$ vagrant up
/Users/tyler/vagrant/ceph2/Vagrantfile:255:in `block in <top (required)>': undefined method `-' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/loader.rb:107:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/loader.rb:107:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/loader.rb:104:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/config/loader.rb:104:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:740:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:740:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:486:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:208:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:473:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:722:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:177:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:177:in `<main>'

**Comment by leseb** [comment] 2016-07-25 12:14
Did you catch up with the recent changes in `vagrant_variables.yml.sample`?
Everything works fine for me on: Vagrant 1.8.1

**Comment by visbits** [comment] 2016-07-26 22:34
Yeah i tried the latest sample with the openstack provider.

The openstack provider needs to support specifying the network in the variable config.  If you have more than 1 network it must be specified.

**Comment by leseb** [comment] 2016-07-27 08:22
I don't use the openstack provider, can you point me to the root cause of the error?

**Comment by leseb** [comment] 2016-08-10 09:58
Closing this, feel free to re-open if the issue is not solved.

**Closed by leseb** 2016-08-10 09:58 UTC

**Comment by hrncir39** [comment] 2016-09-06 12:01
bash init.sh
