### ISSUE TITLE
ceph-common: persist "disable_transparent_hugepage"

### ISSUE THREAD

**Issue by k0ste** [ceph/ceph-ansible#1408] opened 2017-04-03 04:56 UTC
On systemd with [tmpfiles](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) possible execute simple operations on boot, like create/delete/write. So it's possible to set "persist" values on sysfs.

write `never` to `/sys/kernel/mm/transparent_hugepage/enabled`
```
w /sys/kernel/mm/transparent_hugepage/enabled - - - - never
```

If this useful for ceph-ansible I can PR.

**Comment by leseb** [comment] 2017-04-03 16:11
Yes please do a PR for this :).

**Comment by leseb** [comment] 2017-04-03 16:11
Duplicate of https://github.com/ceph/ceph-ansible/issues/1013

**Closed** 2017-04-10 09:07 UTC
