### ISSUE TITLE
nfs-ganesha deb-V2.5-stable not found

### ISSUE THREAD

**Issue by rishabh-d-dave** [ceph/ceph-ansible#3472] opened 2019-01-03 14:32 UTC
**Bug Report**

**What happened:**
`mimic-xenial_cluster` exits unsuccessfully on v3.2.0rc1. Cause for this bug is that ceph-ansible looks at broken link[1](http://download.ceph.com/nfs-ganesha/deb-V2.5-stable/) for nfs-ganesha. 

```
TASK [ceph-nfs : update apt cache] ********************************************************************************************************************************************************************************
^[[1;30mtask path: /home/rishabh/run/ceph-ansible/bz1646456/roles/ceph-nfs/tasks/pre_requisite_non_container.yml:52^[[0m
Monday 31 December 2018  00:54:15 -0500 (0:00:00.886)       0:14:59.311 *******
^[[0;35m[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|changed` use `result is changed`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by ^[[0m
^[[0;35msetting deprecation_warnings=False in ansible.cfg.^[[0m
^[[0;35m[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|success` use `result is success`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by ^[[0m
^[[0;35msetting deprecation_warnings=False in ansible.cfg.^[[0m
^[[1;30mFAILED - RETRYING: update apt cache (5 retries left).^[[0m
^[[1;30mFAILED - RETRYING: update apt cache (4 retries left).^[[0m
^[[1;30mFAILED - RETRYING: update apt cache (3 retries left).^[[0m
^[[1;30mFAILED - RETRYING: update apt cache (2 retries left).^[[0m
^[[1;30mFAILED - RETRYING: update apt cache (1 retries left).^[[0m
^[[0;31mfatal: [nfs0]: FAILED! => {^[[0m
^[[0;31m    "attempts": 5, ^[[0m
^[[0;31m    "changed": false^[[0m
^[[0;31m}^[[0m
^[[0;31m^[[0m
^[[0;31mMSG:^[[0m
^[[0;31m^[[0m
^[[0;31mFailed to update apt cache: W:The repository 'http://download.ceph.com/nfs-ganesha/deb-V2.5-stable/mimic xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://download.ceph.com/nfs-ganesha/deb-V2.5-stable/mimic/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 158.69.68.124 80], E:Failed to fetch http://download.ceph.com/nfs-ganesha/deb-V2.5-stable/mimic/dists/xenial/main/binary-i386/Packages  404  Not Found [IP: 158.69.68.124 80], E:Some index files failed to download. They have been ignored, or old ones used instead.^[[0m
^[[0;31m^[[0m

```

**What you expected to happen:**
ceph-ansible should succeed in finding required version of nfs-ganesha.

**How to reproduce it:**
Run the following command -
```
$ git checkout -b v320rc1 v3.2.0.rc
$ ANSIBLE_FORCE_COLOR=TRUE RELEASE=mimic SCENARIO=xenial_cluster WORKSPACE=./ bash -x ~/ceph-ansible-prs.sh | tee ./mimic-xenial_cluster.log
```

**Environment**:
* OS (e.g. from /etc/os-release): ceph/xenial vagrant box
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 2.6.11
* ceph-ansible version (e.g. `git head or tag or stable branch`): v3.2.0rc1
* Ceph version (e.g. `ceph -v`): mimic

**Comment by ajarr** [comment] 2019-01-03 14:41
duplicate of https://github.com/ceph/ceph-ansible/issues/3178

**Closed by ajarr** 2019-01-03 14:41 UTC
