### ISSUE TITLE
"wait for client.admin key" failed

### ISSUE THREAD

**Issue by davidebelloni** [ceph/ceph-ansible#1173] opened 2016-12-09 16:48 UTC
Hi,
with CoreOS and etcd the following step fail:

> ...
> TASK [ceph-mon : run the ceph monitor docker image] ****************************
> 
> TASK [ceph-mon : run the ceph monitor docker image with kv] ********************
> 
> TASK [ceph-mon : wait for client.admin key exists] *****************************
> fatal: [10.1.2.20]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for file /etc/ceph/ceph-test.client.admin.keyring"}
> fatal: [10.1.2.22]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for file /etc/ceph/ceph-test.client.admin.keyring"}
> fatal: [10.1.2.21]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for file /etc/ceph/ceph-test.client.admin.keyring"}
> 

My setup is:

> mon_containerized_deployment: true
> mon_containerized_deployment_with_kv: true
> mon_containerized_default_ceph_conf_with_kv: true

The problems that I see are the following:

1. with etcd the client.admin key should be on KV store?
2. with this setup which of the following conf keys should be true and which should be false?
```
mon_containerized_deployment
mon_containerized_deployment_with_kv
mon_containerized_default_ceph_conf_with_kv
```
3. the name of the cluster here is "ceph-test", but in the container the file has the following name: /etc/ceph/ceph.client.admin.keyring

Thanks

**Comment by harobed** [comment] 2016-12-13 10:11
Same problem here: http://lists.ceph.com/pipermail/ceph-ansible-ceph.com/2016-December/000007.html

Fixed if I use this revision: https://github.com/ceph/ceph-ansible/commit/7812e0b32ea4ff91cc95a5e4a13e765d5d3aed49

I think there is one regression in last commits.

**Comment by davidebelloni** [comment] 2016-12-13 16:25
Sorry but with revision 7812e0b I have the same issues.
What is you setup and configuration?

Thanks!

**Comment by andrewschoen** [comment] 2016-12-14 16:05
@davidebelloni have you tried without using a custom cluster name? IIRC, the docker deployments have issue with custom cluster names.

**Comment by Logan2211** [comment] 2017-01-06 18:12
I'm seeing this on current `master` branch, but only in a `xenial+hammer` test build scenario. `trusty+hammer`, `trusty+jewel`, and `xenial+jewel` tests in my env do not fail here.

**Comment by vasukulkarni** [comment] 2017-01-06 18:26
I am seeing this in ceph-deploy as well on kraken and master branch,  there is something that is broken in create-keys i guess http://tracker.ceph.com/issues/17352

**Comment by lae** [comment] 2017-01-17 00:38
Based on the issue linked previously, it looks like the implicit execution of `ceph-create-keys` was removed from ceph-mon startup, making it necessary to explicitly run it or generate keys manually. I'm not sure which scenario should be included in the playbook, since it seems the explicit execution of it was removed in #1162 too (, but I'm using the following task at the top of `roles/ceph-mon/tasks/ceph_keys.yml` to get around this for now (I'm not sure if that conditional applies to master branch, though):

```
- name: collect admin and bootstrap keys (for or after kraken release)
  command: ceph-create-keys --cluster {{ cluster }} -i {{ monitor_name }}
  args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring
  failed_when: false
  when:
    - cephx
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.jewel
```

**Comment by leseb** [comment] 2017-01-17 09:03
@Logan2211 any particular reasons to deploy Hammer?
@lae do you mind sending a PR to re-integrate this? Thanks!

**Comment by Logan2211** [comment] 2017-01-30 19:03
@leseb: I was helping someone who was trying to make xenial+hammer go running some scenarios thru my CI and came across it. Figured id share the results since a bug was already open. But no particular reason other than that.. I'm off hammer for a while now so I've got no dog in this one :)

**Comment by leseb** [comment] 2017-01-31 10:36
@Logan2211 thanks for the followup, closing this one :)

**Closed by leseb** 2017-01-31 10:36 UTC
